import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "fr" | "en" | "pt" | "zh";

export const LANGUAGES: { code: Lang; label: string; flag: string }[] = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "zh", label: "中文", flag: "🇨🇳" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
];

// Country -> default language mapping used for automatic locale detection
// (e.g. on public payment pages where the buyer's country is known from the
// `country` query param / merchant country / link country).
const FRENCH_COUNTRIES = new Set([
  "togo", "benin", "bénin", "senegal", "sénégal", "ivory coast", "côte d'ivoire",
  "cote d'ivoire", "mali", "burkina faso", "niger", "guinea", "guinée",
  "cameroon", "cameroun", "gabon", "congo", "drc", "rdc", "chad", "tchad",
  "madagascar", "comoros", "comores", "djibouti", "france", "haiti", "haïti",
]);

const CHINESE_COUNTRIES = new Set([
  "china", "chine", "hong kong", "hongkong", "macau", "macao", "taiwan",
]);

const PORTUGUESE_COUNTRIES = new Set([
  "portugal", "brazil", "brésil", "bresil", "angola", "mozambique",
  "guinea-bissau", "cape verde", "cap-vert",
]);

// English default (explicitly includes India / Pakistan per business requirement,
// plus any country not covered above defaults to English).
export function detectLangFromCountry(country?: string | null): Lang {
  if (!country) return "en";
  const key = country.trim().toLowerCase();
  if (FRENCH_COUNTRIES.has(key)) return "fr";
  if (CHINESE_COUNTRIES.has(key)) return "zh";
  if (PORTUGUESE_COUNTRIES.has(key)) return "pt";
  // India, Pakistan, Nigeria, Ghana, Kenya, USA, UK, etc. => English
  return "en";
}

// Best-effort detection from the browser when no country is known
// (e.g. crypto payment pages with no country field).
export function detectLangFromBrowser(): Lang {
  if (typeof navigator === "undefined") return "en";
  const locale = (navigator.language || (navigator as any).userLanguage || "en").toLowerCase();
  if (locale.startsWith("fr")) return "fr";
  if (locale.startsWith("zh")) return "zh";
  if (locale.startsWith("pt")) return "pt";
  return "en";
}

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Navigation
    overview: "Vue d'ensemble",
    transactions: "Transactions",
    transfers: "Virements",
    withdrawals: "Reversements",
    paymentlinks: "Liens de paiement",
    apikeys: "Clés API",
    webhook: "Webhook",
    settings: "Paramètres",
    navigation: "Navigation",
    merchantSpace: "Espace Marchand",
    notifications: "Notifications",
    messages: "Messages",
    help: "Aide",
    logout: "Déconnexion",
    language: "Langue",
    dashboard: "Tableau de bord",

    // Common
    save: "Enregistrer",
    cancel: "Annuler",
    confirm: "Confirmer",
    delete: "Supprimer",
    edit: "Modifier",
    create: "Créer",
    add: "Ajouter",
    search: "Rechercher",
    filter: "Filtrer",
    export: "Exporter",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    noData: "Aucune donnée",
    actions: "Actions",
    status: "Statut",
    date: "Date",
    amount: "Montant",
    total: "Total",
    copy: "Copier",
    copied: "Copié !",
    active: "Actif",
    inactive: "Inactif",
    activate: "Activer",
    deactivate: "Désactiver",
    all: "Tous",
    yes: "Oui",
    no: "Non",
    optional: "optionnel",
    close: "Fermer",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    submit: "Soumettre",
    reset: "Réinitialiser",
    today: "Aujourd'hui",
    yesterday: "Hier",
    allTime: "Tout",
    refresh: "Actualiser",
    noTransactions: "Aucune transaction",

    // Status
    pending: "En attente",
    approved: "Approuvé",
    rejected: "Rejeté",
    confirmed: "Confirmé",
    failed: "Échoué",
    suspended: "Suspendu",
    completed: "Terminé",
    processing: "En cours",

    // Dashboard Overview
    balance: "Solde",
    reversements: "Reversements",
    todayStats: "Statistique journalier",
    balanceByCountry: "Solde par pays",
    totalVolume: "Volume total",
    transactionCount: "Transactions",
    noCountriesActive: "Aucun pays actif",
    supportContact: "Contact support",
    welcomeBack: "Bienvenue",
    accountBalance: "Solde du compte",

    // Transactions panel
    transactionHistory: "Historique des transactions",
    searchTransactions: "Rechercher par ID, téléphone...",
    filterByStatus: "Filtrer par statut",
    filterByCountry: "Filtrer par pays",
    filterByDate: "Filtrer par date",
    txId: "ID Transaction",
    phone: "Téléphone",
    payer: "Payeur",
    country: "Pays",
    operator: "Opérateur",
    source: "Source",
    noTransactionsFound: "Aucune transaction trouvée",
    noTransactionsDesc: "Vos transactions apparaîtront ici",
    confirmedTransactions: "Transactions confirmées",
    pendingTransactions: "En attente",
    exportCsv: "Exporter CSV",
    transactionDetails: "Détails de la transaction",
    apiPayment: "API Payment",
    paymentLink: "Lien de paiement",
    allStatuses: "Tous les statuts",
    allCountries: "Tous les pays",
    allPeriods: "Toutes les périodes",
    last7days: "7 derniers jours",
    last30days: "30 derniers jours",
    thisMonth: "Ce mois",
    summary: "Résumé",
    recentTransactions: "Transactions récentes",

    // API Keys panel
    apiKeysTitle: "Clés API",
    apiKeysDesc: "Gérez vos clés d'accès par pays",
    yourApiKeys: "Vos clés API",
    apiKey: "Clé API",
    copyKey: "Copier la clé",
    keyActive: "Clé active",
    keyInactive: "Clé inactive",
    noApiKeys: "Aucune clé API",
    noApiKeysDesc: "Contactez votre administrateur pour obtenir une clé API",
    integrationGuide: "Guide d'intégration",
    testPayment: "Tester un paiement",
    copyCode: "Copier le code",
    apiDocumentation: "Documentation API",
    authentication: "Authentification",
    createPayment: "Créer un paiement",
    checkStatus: "Vérifier le statut",
    webhookNotif: "Notification webhook",
    example: "Exemple",

    // Webhook panel
    webhookTitle: "Webhook",
    webhookDesc: "Configurez les notifications automatiques",
    webhookUrl: "URL Webhook",
    webhookSecret: "Secret Webhook",
    webhookUrlPlaceholder: "https://votresite.com/webhook",
    webhookSecretPlaceholder: "Votre clé secrète",
    saveWebhook: "Enregistrer le webhook",
    testWebhook: "Tester le webhook",
    webhookLogs: "Historique des envois",
    noWebhookLogs: "Aucun envoi webhook",
    noWebhookLogsDesc: "Les logs apparaîtront après les premiers paiements",
    webhookNotConfigured: "Aucun webhook configuré",
    webhookActive: "Webhook actif",
    webhookSaved: "Webhook enregistré",
    webhookTested: "Test envoyé",
    event: "Événement",
    responseCode: "Code réponse",
    responseTime: "Temps réponse",
    payload: "Données",
    delivered: "Livré",
    deliveryFailed: "Échec de livraison",
    webhookGuide: "Comment configurer",
    webhookGuideDesc: "Entrez l'URL de votre serveur et le secret. WestPay enverra une notification à chaque transaction.",

    // Withdrawals panel
    withdrawalsTitle: "Reversements",
    withdrawalsDesc: "Retirez vos fonds vers un portefeuille mobile",
    requestWithdrawal: "Demander un reversement",
    withdrawalHistory: "Historique des reversements",
    selectCountry: "Sélectionner un pays",
    selectOperator: "Sélectionner un opérateur",
    enterPhone: "Numéro de téléphone",
    enterAmount: "Montant",
    availableBalance: "Solde disponible",
    withdrawalFees: "Frais",
    netAmount: "Montant net",
    withdrawalMode: "Mode",
    autoMode: "Auto",
    manualMode: "Manuel",
    adminNote: "Note admin",
    omnipayRef: "Réf. Westpay",
    noWithdrawals: "Aucun reversement",
    noWithdrawalsDesc: "Vos demandes de reversement apparaîtront ici",
    totalWithdrawn: "Total retiré",
    pendingWithdrawals: "En attente",
    approvedWithdrawals: "Approuvés",
    fees: "Frais",
    reference: "Référence",

    // Wallet Transfers panel
    walletTransfersTitle: "Virements de solde",
    walletTransfersDesc: "Transférez votre solde entre pays",
    newTransfer: "Nouveau virement",
    fromCountry: "Pays source",
    toCountry: "Pays destination",
    transferAmount: "Montant à transférer",
    transferFee: "Frais de transfert",
    netTransfer: "Montant net reçu",
    confirmTransfer: "Confirmer le virement",
    transferHistory: "Historique des virements",
    noTransfers: "Aucun virement",
    noTransfersDesc: "Vos virements entre pays apparaîtront ici",
    totalTransfers: "Virements",
    transferWarning: "Le virement sera débité immédiatement. L'administrateur doit l'approuver pour créditer le compte destination.",
    selectFromCountry: "Sélectionner le pays source",
    selectToCountry: "Sélectionner le pays destination",

    // Settings panel
    settingsTitle: "Paramètres",
    settingsDesc: "Gérez votre profil et vos préférences",
    profile: "Profil",
    profileInfo: "Informations du profil",
    businessName: "Nom de l'entreprise",
    email: "Email",
    website: "Site web",
    websitePlaceholder: "https://votresite.com",
    securitySection: "Sécurité",
    changePassword: "Changer le mot de passe",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    passwordUpdated: "Mot de passe mis à jour",
    profileUpdated: "Profil mis à jour",
    accountSection: "Mon compte",
    logoutTitle: "Déconnexion",
    logoutDesc: "Vous serez redirigé vers la page de connexion",
    logoutBtn: "Se déconnecter",
    dangerZone: "Zone dangereuse",
    languageSection: "Langue du dashboard",

    // Payment Links panel
    paymentLinksTitle: "Liens de Paiement",
    paymentLinksDesc: "Créez des liens partageables pour recevoir des paiements",
    newLink: "Nouveau lien",
    linkName: "Nom du lien",
    linkNamePlaceholder: "Ex: Paiement commande",
    amountType: "Type de montant",
    fixedAmount: "Montant fixe",
    flexibleAmount: "Montant libre",
    amountCFA: "Montant (F CFA)",
    redirectUrl: "URL de redirection",
    redirectUrlPlaceholder: "https://votresite.com/merci",
    paymentLimit: "Limite de paiements",
    paymentLimitPlaceholder: "Illimité",
    createLink: "Créer le lien",
    editLink: "Modifier le lien",
    saveLink: "Enregistrer",
    noLinks: "Aucun lien de paiement",
    noLinksDesc: "Créez votre premier lien pour recevoir des paiements",
    linksCreated: "Liens créés",
    paymentsReceived: "Paiements reçus",
    totalRevenue: "Volume total",
    linkActive: "Actif",
    linkInactive: "Inactif",
    linkExpired: "Expiré",
    limitReached: "Limite atteinte",
    paymentsCount: "paiements",
    received: "reçus",
    limit: "Limite",
    openLink: "Ouvrir le lien",
    deleteLink: "Supprimer le lien",
    createFirstLink: "Créer un lien",
    fixed: "Fixe",
    flexible: "Libre",

    // Settings extra
    myProfile: "Mon profil",
    merchant: "Marchand",
    statusActive: "Actif",
    security: "Sécurité",
    passwordChanged: "Mot de passe modifié",
    session: "Session",

    // Payment links extra
    linkCreated: "Lien créé",
    linkUpdated: "Lien mis à jour",
    linkDeleted: "Lien supprimé",
    links: "Liens",
    payments: "Paiements",
    volume: "Volume",
    yourLinks: "Vos liens",
    expired: "Expiré",
    unlimited: "Illimité",

    // Wallet panel
    walletTitle: "Solde Wallet",
    walletDesc: "Vue d'ensemble de vos soldes par pays",
    totalConsolidatedBalance: "Solde total consolidé",
    noCountriesConfigured: "Aucun pays configuré",
    countryDisabled: "Pays désactivé",
    cryptoBalances: "Soldes Crypto",
    disabled: "Désactivé",

    // Analyse panel
    analyseTitle: "Analyse",
    analyseDesc: "Performance et statistiques de vos paiements",
    globalStats: "Statistiques globales",
    successRate: "Taux succès",
    confirmedVolume: "Volume confirmé",
    statusBreakdown: "Répartition des statuts",
    statusConfirmed: "Confirmées",
    statusPending: "En attente",
    statusFailed: "Échouées",
    last7daysVolume: "Volume 7 derniers jours",
    performanceByCountry: "Performance par pays",
    todayAndYesterday: "Aujourd'hui & hier",
    transactionSingular: "transaction",
    transactionPlural: "transactions",
    confirmedLabel: "confirmées",
    viewAll: "Voir tout",
    recentTransactionsTitle: "Dernières transactions",
    walletBalance: "Solde wallet",
    successCount: "Succès",
    noFeesLabel: "Sans frais",
    sendMoney: "Envoyer l'argent",
    processingLabel: "Traitement…",
    insufficientFunds: "Solde insuffisant",
    pendingLabel: "En attente",
    confirmedLabel2: "Confirmé",
    failedLabel: "Échoué",

    // Public: language switcher
    chooseLanguage: "Choisir la langue",

    // Public: payment page (payin)
    payTitle: "Paiement",
    payStep1: "Méthode",
    payStep2: "Informations",
    payStep3: "Confirmation",
    payChooseMethod: "Choisissez votre méthode de paiement",
    payMobileMoney: "Mobile Money",
    payCrypto: "Crypto (via OxaPay)",
    payAmountToPay: "Montant à payer",
    payMerchant: "Marchand",
    payCountry: "Pays",
    payFullName: "Nom complet",
    payFullNamePlaceholder: "Votre nom complet",
    payPhoneNumber: "Numéro de téléphone",
    payPhoneNumberPlaceholder: "Ex: 90000000",
    payOperator: "Opérateur",
    payChooseOperator: "Choisissez un opérateur",
    payPayNow: "Payer maintenant",
    payProcessing: "Traitement en cours...",
    paySendingRequest: "Envoi de la demande de paiement...",
    payWaitingValidation: "En attente de validation sur votre téléphone",
    payValidateOnPhone: "Validez le paiement en composant le code USSD reçu sur votre téléphone",
    payValidateOnLink: "Cliquez sur le lien reçu pour valider votre paiement",
    payOpenPaymentLink: "Ouvrir le lien de paiement",
    paySuccess: "Paiement réussi !",
    paySuccessDesc: "Votre paiement a été confirmé avec succès",
    payFailed: "Paiement échoué",
    payFailedDesc: "Le paiement n'a pas pu être confirmé. Veuillez réessayer.",
    payExpired: "Paiement expiré",
    payExpiredDesc: "Le délai de paiement a expiré",
    payTryAgain: "Réessayer",
    payBackToMerchant: "Retour au marchand",
    via: "via",
    time: "Heure",
    payMethodRequired: "Méthode requise",
    payMethodRequiredDesc: "Veuillez choisir une méthode de paiement",
    payNameRequired: "Nom requis",
    payPhoneRequired: "Téléphone requis",
    payOperatorRequired: "Opérateur requis",
    payInvalidPhone: "Numéro de téléphone invalide",
    payErrorTitle: "Erreur",
    payErrorGeneric: "Une erreur est survenue. Veuillez réessayer.",
    payTransactionRef: "Référence",
    payDate: "Date",
    payLinkNotFound: "Lien de paiement introuvable",
    payLinkExpired: "Ce lien de paiement a expiré",
    payLinkInactive: "Ce lien de paiement est désactivé",
    payLinkLimitReached: "Ce lien de paiement a atteint sa limite de paiements",
    payEnterAmount: "Entrez le montant",
    payEnterAmountDesc: "Ce lien accepte un montant libre",
    payMerchantNotFound: "Marchand introuvable",
    payContinue: "Continuer",
    payChangeLanguage: "Changer de langue",
    payHelp: "Aide",
    payInvalidLink: "Lien invalide",
    payInvalidAmount: "Veuillez saisir un montant valide",
    payChooseOperatorDesc: "Sélectionnez un opérateur pour continuer",
    payPhoneNumberDesc: "Votre numéro",
    paySecurityRobotPay: "Sécurité RobotPay",
    payVerificationInProgress: "Vérification en cours...",
    payWaitingConfirmation: "Paiement en attente de confirmation",
    payProcessingRequestBy: "Traitement de votre demande par",
    payDoNotClosePage: "Ne fermez pas cette page",
    payRedirectionIn: "Redirection vers le marchand dans",
    payRedirectionSeconds: "secondes...",
    payRedirectionClickIfNo: "Cliquez ici si vous n'êtes pas redirigé",
    payCancel: "Annuler",
    payConfirmPayment: "Confirmer le paiement",
    payOrangeMoneyBurkinaCote: "Code de vérification",
    payOrangeMoneyBurkinaDesc: "Pour Orange Money Burkina Faso, générez un code de paiement en composant *144*4*6*montant# puis entrez-le ci-dessous.",
    payOrangeMoneyCoteDesc: "Pour Orange Money Côte d'Ivoire, générez un code de paiement en composant #144*82# puis entrez-le ci-dessous.",
    payOrangeMoneyEnterCode: "Entrez le code de paiement",
    payCustomerSupport: "Assistance Client",
    payAnyQuestion: "Une question ? Besoin d'aide pour votre paiement ?",
    payYourName: "Votre nom",
    payYourWhatsApp: "Votre WhatsApp (avec indicatif)",
    payDescribeProblem: "Décrivez votre problème...",
    payMessageSent: "Message envoyé ! Notre équipe vous contactera sous peu.",
    paySendMessage: "Envoyer le message",

    // Public: OTP modal
    otpTitle: "Code de vérification",
    otpDesc: "Un code de vérification a été envoyé à votre téléphone",
    otpEnterCode: "Entrez le code reçu",
    otpCodePlaceholder: "Code OTP",
    otpCodeRequired: "Code OTP requis",
    otpInvalidCode: "Code OTP invalide",
    otpVerify: "Vérifier",
    otpVerifying: "Vérification...",
    otpResend: "Renvoyer le code",
    otpResendIn: "Renvoyer dans",
    otpResent: "Code renvoyé",
    otpTimeExpired: "Le délai a expiré, veuillez recommencer",

    // Public: crypto payment page
    cryptoPayTitle: "Paiement Crypto",
    cryptoScanQr: "Scannez le QR code pour payer",
    cryptoWalletAddress: "Adresse du portefeuille",
    cryptoAmountToSend: "Montant à envoyer",
    cryptoCopyAddress: "Copier l'adresse",
    cryptoAddressCopied: "Adresse copiée",
    cryptoTimeRemaining: "Temps restant",
    cryptoWaitingPayment: "En attente du paiement...",
    cryptoConfirmed: "Paiement confirmé",
    cryptoExpiredTitle: "Session expirée",
    cryptoExpiredDesc: "Le délai de paiement a expiré, veuillez générer une nouvelle facture",
    cryptoNetwork: "Réseau",
    cryptoTrackId: "ID de suivi",
    cryptoStatusWaiting: "En attente de paiement",
    cryptoStatusConfirming: "Confirmation en cours",
    cryptoStatusPaying: "Paiement reçu",
    cryptoStatusPaid: "Paiement confirmé ✓",
    cryptoStatusExpired: "Lien expiré",
    cryptoStatusFailed: "Paiement échoué",
    cryptoStatusRefunded: "Remboursé",
    cryptoStatusDetected: "Transaction détectée !",
    cryptoStatusConfirmingBlockchain: "Confirmation en cours sur la blockchain…",
    cryptoPaidDesc: "Votre transaction a été confirmée sur la blockchain.",
    cryptoTxHash: "Hash de transaction",
    cryptoWarning: "⚠️ Envoyez exactement le montant indiqué sur le bon réseau. Toute erreur peut entraîner une perte définitive des fonds.",
    cryptoScanWallet: "Scannez avec votre wallet crypto",
    cryptoDepositAddress: "Adresse de dépôt",
    cryptoSecurePayment: "Paiement sécurisé",
    cryptoStepInfo: "Informations",
    cryptoStepPayment: "Paiement",
    cryptoMerchant: "Marchand",
    cryptoPurpose: "Objet du paiement",
    cryptoCurrency: "Devise de paiement",
    cryptoAmountToPay: "Montant à payer",
    cryptoPayNow: "Payer maintenant",
    cryptoPreparing: "Préparation du paiement…",
    cryptoExactAmount: "Montant exact à envoyer",
    cryptoLinkNotFound: "Page introuvable",
    cryptoLinkInvalid: "Ce lien de paiement n'est pas valide.",
    cryptoFreeAmount: "Montant libre",
    cryptoStep: "Étape",
    cryptoOf: "sur",

    // Public: API docs
    docsTitle: "Documentation API",
    docsSubtitle: "Intégrez WestPay à votre application",
    docsIntro: "Bienvenue dans la documentation de l'API WestPay",
    docsPinTitle: "Accès protégé",
    docsPinDesc: "Entrez votre PIN à 6 chiffres pour accéder à la documentation",
    docsPinPlaceholder: "PIN à 6 chiffres",
    docsAccess: "Accéder",
    docsInvalidPin: "PIN invalide",
    docsGettingStarted: "Démarrage",
    docsEndpoints: "Points de terminaison",
    docsRequestBody: "Corps de la requête",
    docsResponse: "Réponse",
    docsParameters: "Paramètres",
    docsRequired: "Requis",
    docsRestricted: "Usage restreint",
    docsAccessTitle: "Accès Documentation",
    docsAccessDesc: "Entrez vos identifiants marchands pour accéder à la documentation API.",
    docsEmailLabel: "Adresse email",
    docsPinLabel: "Code PIN (6 chiffres)",
    docsShowPin: "Afficher le PIN",
    docsHidePin: "Masquer le PIN",
    docsSecurityCode: "Code de sécurité",
    docsCaptchaPlaceholder: "Entrez le code ci-dessus",
    docsCaptchaError: "Code incorrect, un nouveau code a été généré.",
    docsVerifying: "Vérification...",
    docsAccessBtn: "Accéder à la documentation",
    docsSecuredAccess: "Accès sécurisé",
    docsPinConfigured: "Votre PIN est configuré par l'administrateur. Chaque accès est journalisé.",
    docsSecuredDocs: "Documentation sécurisée",
    docsIntegrationTitle: "Intégrez RobotPay dans vos applications",
    docsIntegrationDesc: "Accédez à la documentation complète de notre API de paiement Mobile Money pour l'Afrique de l'Ouest et du Centre.",
    docsFeature1: "Documentation complète de l'API RobotPay",
    docsFeature2: "Exemples de code prêts à intégrer",
    docsFeature3: "Gestion de vos clés API par pays",
    docsFeature4: "Accès sécurisé par PIN personnel",
    cryptoDocsTitle: "Documentation API Crypto",
    cryptoDocsSubtitle: "RobotPay — Paiements cryptomonnaies",
    cryptoDocsIntroTitle: "Introduction",
    cryptoDocsIntroSubtitle: "RobotPay Crypto API — Acceptez des paiements en cryptomonnaies",
    cryptoDocsIntroDesc: "L'API RobotPay Crypto vous permet d'accepter des paiements en cryptomonnaies (USDT, BTC, ETH, LTC, TRX et plus) de manière simple et sécurisée. Vos clients peuvent payer en crypto depuis n'importe quel pays, sans restriction géographique.",
    cryptoDocsGlobalTitle: "Mondial",
    cryptoDocsGlobalDesc: "Paiements sans frontières depuis n'importe quel pays",
    cryptoDocsInstantTitle: "Instantané",
    cryptoDocsInstantDesc: "Confirmations automatiques via notre système temps réel",
    cryptoDocsSecureTitle: "Sécurisé",
    cryptoDocsSecureDesc: "Chiffrement HMAC-SHA256, aucun stockage de clés privées",
    cryptoDocsFeesTitle: "Frais de service",
    cryptoDocsFeesDesc: "5% sur chaque dépôt reçu · 5% sur chaque retrait effectué",
    cryptoDocsSupportedTitle: "Cryptomonnaies supportées",
    cryptoDocsCredentialsTitle: "Mes identifiants",
    cryptoDocsEnabled: "Paiements crypto activés sur votre compte",
    cryptoDocsDisabled: "Paiements crypto non activés — contactez l'administrateur",
    cryptoDocsSlugLabel: "Votre slug (identifiant public)",
    cryptoDocsApiKeyLabel: "Votre clé API crypto",
    cryptoDocsPaymentPageLabel: "URL de paiement (votre page)",
    cryptoDocsNoApiKey: "Clé API non encore générée — rendez-vous dans votre tableau de bord → Crypto → API",
    cryptoDocsHowToUseApiKey: "Comment utiliser la clé API",
    cryptoDocsAddHeader: "Ajoutez le header suivant à chaque requête API protégée :",
    cryptoDocsSlugTitle: "Lien de paiement (sans code)",
    cryptoDocsSlugSubtitle: "Solution simple — redirigez vos clients sans appeler l'API",
    cryptoDocsSlugDesc: "La méthode la plus simple : construisez une URL avec votre slug et les paramètres du paiement. RobotPay crée automatiquement l'invoice et affiche la page de paiement crypto à votre client.",
    cryptoDocsUrlStructure: "Structure de l'URL",
    cryptoDocsParameters: "Paramètres",
    cryptoDocsParamName: "Paramètre",
    cryptoDocsParamRequired: "Requis",
    cryptoDocsParamDesc: "Description",
    cryptoDocsExamples: "Exemples concrets",
    cryptoDocsHtmlButton: "Bouton HTML à intégrer sur votre site",
    cryptoDocsInvoiceTitle: "Créer une invoice (API)",
    cryptoDocsInvoiceSubtitle: "Pour les intégrations avancées — contrôle total depuis votre backend",
  },

  en: {
    // Navigation
    overview: "Overview",
    transactions: "Transactions",
    transfers: "Transfers",
    withdrawals: "Withdrawals",
    paymentlinks: "Payment Links",
    apikeys: "API Keys",
    webhook: "Webhook",
    settings: "Settings",
    navigation: "Navigation",
    merchantSpace: "Merchant Space",
    notifications: "Notifications",
    messages: "Messages",
    help: "Help",
    logout: "Logout",
    language: "Language",
    dashboard: "Dashboard",

    // Common
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    add: "Add",
    search: "Search",
    filter: "Filter",
    export: "Export",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    noData: "No data",
    actions: "Actions",
    status: "Status",
    date: "Date",
    amount: "Amount",
    total: "Total",
    copy: "Copy",
    copied: "Copied!",
    active: "Active",
    inactive: "Inactive",
    activate: "Activate",
    deactivate: "Deactivate",
    all: "All",
    yes: "Yes",
    no: "No",
    optional: "optional",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    reset: "Reset",
    today: "Today",
    yesterday: "Yesterday",
    allTime: "All time",
    refresh: "Refresh",
    noTransactions: "No transactions",

    // Status
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    confirmed: "Confirmed",
    failed: "Failed",
    suspended: "Suspended",
    completed: "Completed",
    processing: "Processing",

    // Dashboard Overview
    balance: "Balance",
    reversements: "Withdrawals",
    todayStats: "Daily Statistics",
    balanceByCountry: "Balance by Country",
    totalVolume: "Total volume",
    transactionCount: "Transactions",
    noCountriesActive: "No active countries",
    supportContact: "Support contact",
    welcomeBack: "Welcome back",
    accountBalance: "Account balance",

    // Transactions panel
    transactionHistory: "Transaction history",
    searchTransactions: "Search by ID, phone...",
    filterByStatus: "Filter by status",
    filterByCountry: "Filter by country",
    filterByDate: "Filter by date",
    txId: "Transaction ID",
    phone: "Phone",
    payer: "Payer",
    country: "Country",
    operator: "Operator",
    source: "Source",
    noTransactionsFound: "No transactions found",
    noTransactionsDesc: "Your transactions will appear here",
    confirmedTransactions: "Confirmed transactions",
    pendingTransactions: "Pending",
    exportCsv: "Export CSV",
    transactionDetails: "Transaction details",
    apiPayment: "API Payment",
    paymentLink: "Payment Link",
    allStatuses: "All statuses",
    allCountries: "All countries",
    allPeriods: "All periods",
    last7days: "Last 7 days",
    last30days: "Last 30 days",
    thisMonth: "This month",
    summary: "Summary",
    recentTransactions: "Recent transactions",

    // API Keys panel
    apiKeysTitle: "API Keys",
    apiKeysDesc: "Manage your access keys by country",
    yourApiKeys: "Your API keys",
    apiKey: "API Key",
    copyKey: "Copy key",
    keyActive: "Active key",
    keyInactive: "Inactive key",
    noApiKeys: "No API keys",
    noApiKeysDesc: "Contact your administrator to get an API key",
    integrationGuide: "Integration guide",
    testPayment: "Test a payment",
    copyCode: "Copy code",
    apiDocumentation: "API Documentation",
    authentication: "Authentication",
    createPayment: "Create payment",
    checkStatus: "Check status",
    webhookNotif: "Webhook notification",
    example: "Example",

    // Webhook panel
    webhookTitle: "Webhook",
    webhookDesc: "Configure automatic notifications",
    webhookUrl: "Webhook URL",
    webhookSecret: "Webhook Secret",
    webhookUrlPlaceholder: "https://yoursite.com/webhook",
    webhookSecretPlaceholder: "Your secret key",
    saveWebhook: "Save webhook",
    testWebhook: "Test webhook",
    webhookLogs: "Delivery history",
    noWebhookLogs: "No webhook deliveries",
    noWebhookLogsDesc: "Logs will appear after the first payments",
    webhookNotConfigured: "No webhook configured",
    webhookActive: "Webhook active",
    webhookSaved: "Webhook saved",
    webhookTested: "Test sent",
    event: "Event",
    responseCode: "Response code",
    responseTime: "Response time",
    payload: "Payload",
    delivered: "Delivered",
    deliveryFailed: "Delivery failed",
    webhookGuide: "How to configure",
    webhookGuideDesc: "Enter your server URL and secret. WestPay will send a notification for each transaction.",

    // Withdrawals panel
    withdrawalsTitle: "Withdrawals",
    withdrawalsDesc: "Withdraw your funds to a mobile wallet",
    requestWithdrawal: "Request withdrawal",
    withdrawalHistory: "Withdrawal history",
    selectCountry: "Select a country",
    selectOperator: "Select an operator",
    enterPhone: "Phone number",
    enterAmount: "Amount",
    availableBalance: "Available balance",
    withdrawalFees: "Fees",
    netAmount: "Net amount",
    withdrawalMode: "Mode",
    autoMode: "Auto",
    manualMode: "Manual",
    adminNote: "Admin note",
    omnipayRef: "Westpay Ref.",
    noWithdrawals: "No withdrawals",
    noWithdrawalsDesc: "Your withdrawal requests will appear here",
    totalWithdrawn: "Total withdrawn",
    pendingWithdrawals: "Pending",
    approvedWithdrawals: "Approved",
    fees: "Fees",
    reference: "Reference",

    // Wallet Transfers panel
    walletTransfersTitle: "Balance Transfers",
    walletTransfersDesc: "Transfer your balance between countries",
    newTransfer: "New transfer",
    fromCountry: "Source country",
    toCountry: "Destination country",
    transferAmount: "Transfer amount",
    transferFee: "Transfer fee",
    netTransfer: "Net amount received",
    confirmTransfer: "Confirm transfer",
    transferHistory: "Transfer history",
    noTransfers: "No transfers",
    noTransfersDesc: "Your country-to-country transfers will appear here",
    totalTransfers: "Transfers",
    transferWarning: "The transfer will be debited immediately. The administrator must approve it to credit the destination account.",
    selectFromCountry: "Select source country",
    selectToCountry: "Select destination country",

    // Settings panel
    settingsTitle: "Settings",
    settingsDesc: "Manage your profile and preferences",
    profile: "Profile",
    profileInfo: "Profile information",
    businessName: "Business name",
    email: "Email",
    website: "Website",
    websitePlaceholder: "https://yoursite.com",
    securitySection: "Security",
    changePassword: "Change password",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Confirm new password",
    passwordUpdated: "Password updated",
    profileUpdated: "Profile updated",
    accountSection: "My account",
    logoutTitle: "Logout",
    logoutDesc: "You will be redirected to the login page",
    logoutBtn: "Sign out",
    dangerZone: "Danger zone",
    languageSection: "Dashboard language",

    // Payment Links panel
    paymentLinksTitle: "Payment Links",
    paymentLinksDesc: "Create shareable links to receive payments",
    newLink: "New link",
    linkName: "Link name",
    linkNamePlaceholder: "Ex: Order payment",
    amountType: "Amount type",
    fixedAmount: "Fixed amount",
    flexibleAmount: "Flexible amount",
    amountCFA: "Amount (FCFA)",
    redirectUrl: "Redirect URL",
    redirectUrlPlaceholder: "https://yoursite.com/thank-you",
    paymentLimit: "Payment limit",
    paymentLimitPlaceholder: "Unlimited",
    createLink: "Create link",
    editLink: "Edit link",
    saveLink: "Save",
    noLinks: "No payment links",
    noLinksDesc: "Create your first link to start receiving payments",
    linksCreated: "Links created",
    paymentsReceived: "Payments received",
    totalRevenue: "Total volume",
    linkActive: "Active",
    linkInactive: "Inactive",
    linkExpired: "Expired",
    limitReached: "Limit reached",
    paymentsCount: "payments",
    received: "received",
    limit: "Limit",
    openLink: "Open link",
    deleteLink: "Delete link",
    createFirstLink: "Create a link",
    fixed: "Fixed",
    flexible: "Flexible",

    // Settings extra
    myProfile: "My profile",
    merchant: "Merchant",
    statusActive: "Active",
    security: "Security",
    passwordChanged: "Password changed",
    session: "Session",

    // Payment links extra
    linkCreated: "Link created",
    linkUpdated: "Link updated",
    linkDeleted: "Link deleted",
    links: "Links",
    payments: "Payments",
    volume: "Volume",
    yourLinks: "Your links",
    expired: "Expired",
    unlimited: "Unlimited",

    // Wallet panel
    walletTitle: "Wallet Balance",
    walletDesc: "Overview of your balances by country",
    totalConsolidatedBalance: "Total consolidated balance",
    noCountriesConfigured: "No countries configured",
    countryDisabled: "Country disabled",
    cryptoBalances: "Crypto Balances",
    disabled: "Disabled",

    // Analyse panel
    analyseTitle: "Analytics",
    analyseDesc: "Payment performance and statistics",
    globalStats: "Global statistics",
    successRate: "Success rate",
    confirmedVolume: "Confirmed volume",
    statusBreakdown: "Status breakdown",
    statusConfirmed: "Confirmed",
    statusPending: "Pending",
    statusFailed: "Failed",
    last7daysVolume: "Volume over last 7 days",
    performanceByCountry: "Performance by country",
    todayAndYesterday: "Today & yesterday",
    transactionSingular: "transaction",
    transactionPlural: "transactions",
    confirmedLabel: "confirmed",
    viewAll: "View all",
    recentTransactionsTitle: "Recent transactions",
    walletBalance: "Wallet balance",
    successCount: "Success",
    noFeesLabel: "No fees",
    sendMoney: "Send money",
    processingLabel: "Processing…",
    insufficientFunds: "Insufficient balance",
    pendingLabel: "Pending",
    confirmedLabel2: "Confirmed",
    failedLabel: "Failed",

    // Public: language switcher
    chooseLanguage: "Choose language",

    // Public: payment page (payin)
    payTitle: "Payment",
    payStep1: "Method",
    payStep2: "Details",
    payStep3: "Confirmation",
    payChooseMethod: "Choose your payment method",
    payMobileMoney: "Mobile Money",
    payCrypto: "Crypto (via OxaPay)",
    payAmountToPay: "Amount to pay",
    payMerchant: "Merchant",
    payCountry: "Country",
    payFullName: "Full name",
    payFullNamePlaceholder: "Your full name",
    payPhoneNumber: "Phone number",
    payPhoneNumberPlaceholder: "Ex: 90000000",
    payOperator: "Operator",
    payChooseOperator: "Choose an operator",
    payPayNow: "Pay now",
    payProcessing: "Processing...",
    paySendingRequest: "Sending payment request...",
    payWaitingValidation: "Waiting for validation on your phone",
    payValidateOnPhone: "Validate the payment by dialing the USSD code received on your phone",
    payValidateOnLink: "Click the link received to validate your payment",
    payOpenPaymentLink: "Open payment link",
    paySuccess: "Payment successful!",
    paySuccessDesc: "Your payment has been confirmed successfully",
    payFailed: "Payment failed",
    payFailedDesc: "The payment could not be confirmed. Please try again.",
    payExpired: "Payment expired",
    payExpiredDesc: "The payment window has expired",
    payTryAgain: "Try again",
    payBackToMerchant: "Back to merchant",
    via: "via",
    time: "Time",
    payMethodRequired: "Method required",
    payMethodRequiredDesc: "Please choose a payment method",
    payNameRequired: "Name required",
    payPhoneRequired: "Phone required",
    payOperatorRequired: "Operator required",
    payInvalidPhone: "Invalid phone number",
    payErrorTitle: "Error",
    payErrorGeneric: "An error occurred. Please try again.",
    payTransactionRef: "Reference",
    payDate: "Date",
    payLinkNotFound: "Payment link not found",
    payLinkExpired: "This payment link has expired",
    payLinkInactive: "This payment link is disabled",
    payLinkLimitReached: "This payment link has reached its payment limit",
    payEnterAmount: "Enter amount",
    payEnterAmountDesc: "This link accepts a flexible amount",
    payMerchantNotFound: "Merchant not found",
    payContinue: "Continue",
    payChangeLanguage: "Change language",
    payHelp: "Help",
    payInvalidLink: "Invalid link",
    payInvalidAmount: "Please enter a valid amount",
    payChooseOperatorDesc: "Select an operator to continue",
    payPhoneNumberDesc: "Your number",
    paySecurityRobotPay: "RobotPay Security",
    payVerificationInProgress: "Verification in progress...",
    payWaitingConfirmation: "Payment waiting for confirmation",
    payProcessingRequestBy: "Processing your request by",
    payDoNotClosePage: "Do not close this page",
    payRedirectionIn: "Redirection to merchant in",
    payRedirectionSeconds: "seconds...",
    payRedirectionClickIfNo: "Click here if you are not redirected",
    payCancel: "Cancel",
    payConfirmPayment: "Confirm payment",
    payOrangeMoneyBurkinaCote: "Verification code",
    payOrangeMoneyBurkinaDesc: "For Orange Money Burkina Faso, generate a payment code by dialing *144*4*6*amount# then enter it below.",
    payOrangeMoneyCoteDesc: "For Orange Money Côte d'Ivoire, generate a payment code by dialing #144*82# then enter it below.",
    payOrangeMoneyEnterCode: "Enter the payment code",
    payCustomerSupport: "Customer Support",
    payAnyQuestion: "Any question? Need help with your payment?",
    payYourName: "Your name",
    payYourWhatsApp: "Your WhatsApp (with country code)",
    payDescribeProblem: "Describe your problem...",
    payMessageSent: "Message sent! Our team will contact you shortly.",
    paySendMessage: "Send message",

    // Public: OTP modal
    otpTitle: "Verification code",
    otpDesc: "A verification code has been sent to your phone",
    otpEnterCode: "Enter the code you received",
    otpCodePlaceholder: "OTP code",
    otpCodeRequired: "OTP code required",
    otpInvalidCode: "Invalid OTP code",
    otpVerify: "Verify",
    otpVerifying: "Verifying...",
    otpResend: "Resend code",
    otpResendIn: "Resend in",
    otpResent: "Code resent",
    otpTimeExpired: "The time has expired, please start again",

    // Public: crypto payment page
    cryptoPayTitle: "Crypto Payment",
    cryptoScanQr: "Scan the QR code to pay",
    cryptoWalletAddress: "Wallet address",
    cryptoAmountToSend: "Amount to send",
    cryptoCopyAddress: "Copy address",
    cryptoAddressCopied: "Address copied",
    cryptoTimeRemaining: "Time remaining",
    cryptoWaitingPayment: "Waiting for payment...",
    cryptoConfirmed: "Payment confirmed",
    cryptoExpiredTitle: "Session expired",
    cryptoExpiredDesc: "The payment window has expired, please generate a new invoice",
    cryptoNetwork: "Network",
    cryptoTrackId: "Track ID",
    cryptoStatusWaiting: "Waiting for payment",
    cryptoStatusConfirming: "Confirming",
    cryptoStatusPaying: "Payment received",
    cryptoStatusPaid: "Payment confirmed ✓",
    cryptoStatusExpired: "Link expired",
    cryptoStatusFailed: "Payment failed",
    cryptoStatusRefunded: "Refunded",
    cryptoStatusDetected: "Transaction detected!",
    cryptoStatusConfirmingBlockchain: "Confirming on the blockchain…",
    cryptoPaidDesc: "Your transaction has been confirmed on the blockchain.",
    cryptoTxHash: "Transaction hash",
    cryptoWarning: "⚠️ Send exactly the indicated amount on the correct network. Any error may result in permanent loss of funds.",
    cryptoScanWallet: "Scan with your crypto wallet",
    cryptoDepositAddress: "Deposit address",
    cryptoSecurePayment: "Secure payment",
    cryptoStepInfo: "Information",
    cryptoStepPayment: "Payment",
    cryptoMerchant: "Merchant",
    cryptoPurpose: "Purpose of payment",
    cryptoCurrency: "Payment currency",
    cryptoAmountToPay: "Amount to pay",
    cryptoPayNow: "Pay now",
    cryptoPreparing: "Preparing payment…",
    cryptoExactAmount: "Exact amount to send",
    cryptoLinkNotFound: "Page not found",
    cryptoLinkInvalid: "This payment link is not valid.",
    cryptoFreeAmount: "Free amount",
    cryptoStep: "Step",
    cryptoOf: "of",

    // Public: API docs
    docsTitle: "API Documentation",
    docsSubtitle: "Integrate WestPay into your application",
    docsIntro: "Welcome to the WestPay API documentation",
    docsPinTitle: "Protected access",
    docsPinDesc: "Enter your 6-digit PIN to access the documentation",
    docsPinPlaceholder: "6-digit PIN",
    docsAccess: "Access",
    docsInvalidPin: "Invalid PIN",
    docsGettingStarted: "Getting started",
    docsEndpoints: "Endpoints",
    docsRequestBody: "Request body",
    docsResponse: "Response",
    docsParameters: "Parameters",
    docsRequired: "Required",
    docsRestricted: "Restricted use",
    docsAccessTitle: "Documentation Access",
    docsAccessDesc: "Enter your merchant credentials to access the API documentation.",
    docsEmailLabel: "Email address",
    docsPinLabel: "PIN Code (6 digits)",
    docsShowPin: "Show PIN",
    docsHidePin: "Hide PIN",
    docsSecurityCode: "Security code",
    docsCaptchaPlaceholder: "Enter the code above",
    docsCaptchaError: "Incorrect code, a new code has been generated.",
    docsVerifying: "Verifying...",
    docsAccessBtn: "Access documentation",
    docsSecuredAccess: "Secured access",
    docsPinConfigured: "Your PIN is configured by the administrator. Every access is logged.",
    docsSecuredDocs: "Secured documentation",
    docsIntegrationTitle: "Integrate RobotPay into your applications",
    docsIntegrationDesc: "Access the complete documentation of our Mobile Money payment API for West and Central Africa.",
    docsFeature1: "Complete RobotPay API documentation",
    docsFeature2: "Ready-to-integrate code samples",
    docsFeature3: "Manage your API keys by country",
    docsFeature4: "Secured access via personal PIN",
    cryptoDocsTitle: "Crypto API Documentation",
    cryptoDocsSubtitle: "RobotPay — Cryptocurrency payments",
    cryptoDocsIntroTitle: "Introduction",
    cryptoDocsIntroSubtitle: "RobotPay Crypto API — Accept cryptocurrency payments",
    cryptoDocsIntroDesc: "The RobotPay Crypto API allows you to accept cryptocurrency payments (USDT, BTC, ETH, LTC, TRX and more) simply and securely. Your customers can pay in crypto from any country, without geographic restrictions.",
    cryptoDocsGlobalTitle: "Global",
    cryptoDocsGlobalDesc: "Borderless payments from any country",
    cryptoDocsInstantTitle: "Instant",
    cryptoDocsInstantDesc: "Automatic confirmations via our real-time system",
    cryptoDocsSecureTitle: "Secure",
    cryptoDocsSecureDesc: "HMAC-SHA256 encryption, no private key storage",
    cryptoDocsFeesTitle: "Service fees",
    cryptoDocsFeesDesc: "5% on each deposit received · 5% on each withdrawal made",
    cryptoDocsSupportedTitle: "Supported cryptocurrencies",
    cryptoDocsCredentialsTitle: "My credentials",
    cryptoDocsEnabled: "Crypto payments enabled on your account",
    cryptoDocsDisabled: "Crypto payments not enabled — contact administrator",
    cryptoDocsSlugLabel: "Your slug (public identifier)",
    cryptoDocsApiKeyLabel: "Your crypto API key",
    cryptoDocsPaymentPageLabel: "Payment URL (your page)",
    cryptoDocsNoApiKey: "API key not yet generated — go to your dashboard → Crypto → API",
    cryptoDocsHowToUseApiKey: "How to use the API key",
    cryptoDocsAddHeader: "Add the following header to each protected API request:",
    cryptoDocsSlugTitle: "Payment link (no-code)",
    cryptoDocsSlugSubtitle: "Simple solution — redirect your customers without calling the API",
    cryptoDocsSlugDesc: "The simplest method: build a URL with your slug and payment parameters. RobotPay automatically creates the invoice and displays the crypto payment page to your customer.",
    cryptoDocsUrlStructure: "URL structure",
    cryptoDocsParameters: "Parameters",
    cryptoDocsParamName: "Parameter",
    cryptoDocsParamRequired: "Required",
    cryptoDocsParamDesc: "Description",
    cryptoDocsExamples: "Concrete examples",
    cryptoDocsHtmlButton: "HTML button to integrate on your site",
    cryptoDocsInvoiceTitle: "Create an invoice (API)",
    cryptoDocsInvoiceSubtitle: "For advanced integrations — full control from your backend",
  },

  zh: {
    // Navigation
    overview: "概览",
    transactions: "交易",
    transfers: "转账",
    withdrawals: "提现",
    paymentlinks: "支付链接",
    apikeys: "API 密钥",
    webhook: "Webhook",
    settings: "设置",
    navigation: "导航",
    merchantSpace: "商户空间",
    notifications: "通知",
    messages: "消息",
    help: "帮助",
    logout: "退出登录",
    language: "语言",
    dashboard: "仪表盘",

    // Common
    save: "保存",
    cancel: "取消",
    confirm: "确认",
    delete: "删除",
    edit: "编辑",
    create: "创建",
    add: "添加",
    search: "搜索",
    filter: "筛选",
    export: "导出",
    loading: "加载中...",
    error: "错误",
    success: "成功",
    noData: "暂无数据",
    actions: "操作",
    status: "状态",
    date: "日期",
    amount: "金额",
    total: "总计",
    copy: "复制",
    copied: "已复制！",
    active: "启用",
    inactive: "禁用",
    activate: "启用",
    deactivate: "停用",
    all: "全部",
    yes: "是",
    no: "否",
    optional: "可选",
    close: "关闭",
    back: "返回",
    next: "下一步",
    previous: "上一步",
    submit: "提交",
    reset: "重置",
    today: "今天",
    yesterday: "昨天",
    allTime: "全部时间",
    refresh: "刷新",
    noTransactions: "暂无交易",

    // Status
    pending: "待处理",
    approved: "已批准",
    rejected: "已拒绝",
    confirmed: "已确认",
    failed: "失败",
    suspended: "已暂停",
    completed: "已完成",
    processing: "处理中",

    // Dashboard Overview
    balance: "余额",
    reversements: "提现",
    todayStats: "每日统计",
    balanceByCountry: "按国家显示余额",
    totalVolume: "总交易额",
    transactionCount: "交易数量",
    noCountriesActive: "没有已启用的国家",
    supportContact: "联系客服",
    welcomeBack: "欢迎回来",
    accountBalance: "账户余额",

    // Transactions panel
    transactionHistory: "交易记录",
    searchTransactions: "按ID、电话号码搜索...",
    filterByStatus: "按状态筛选",
    filterByCountry: "按国家筛选",
    filterByDate: "按日期筛选",
    txId: "交易编号",
    phone: "电话",
    payer: "付款人",
    country: "国家",
    operator: "运营商",
    source: "来源",
    noTransactionsFound: "未找到交易",
    noTransactionsDesc: "您的交易将显示在此处",
    confirmedTransactions: "已确认交易",
    pendingTransactions: "待处理",
    exportCsv: "导出 CSV",
    transactionDetails: "交易详情",
    apiPayment: "API 支付",
    paymentLink: "支付链接",
    allStatuses: "所有状态",
    allCountries: "所有国家",
    allPeriods: "所有时段",
    last7days: "最近7天",
    last30days: "最近30天",
    thisMonth: "本月",
    summary: "摘要",
    recentTransactions: "最近交易",

    // API Keys panel
    apiKeysTitle: "API 密钥",
    apiKeysDesc: "按国家管理您的访问密钥",
    yourApiKeys: "您的 API 密钥",
    apiKey: "API 密钥",
    copyKey: "复制密钥",
    keyActive: "密钥已启用",
    keyInactive: "密钥已禁用",
    noApiKeys: "暂无 API 密钥",
    noApiKeysDesc: "请联系管理员获取 API 密钥",
    integrationGuide: "集成指南",
    testPayment: "测试支付",
    copyCode: "复制代码",
    apiDocumentation: "API 文档",
    authentication: "身份验证",
    createPayment: "创建支付",
    checkStatus: "查询状态",
    webhookNotif: "Webhook 通知",
    example: "示例",

    // Webhook panel
    webhookTitle: "Webhook",
    webhookDesc: "配置自动通知",
    webhookUrl: "Webhook 地址",
    webhookSecret: "Webhook 密钥",
    webhookUrlPlaceholder: "https://yoursite.com/webhook",
    webhookSecretPlaceholder: "您的密钥",
    saveWebhook: "保存 Webhook",
    testWebhook: "测试 Webhook",
    webhookLogs: "发送记录",
    noWebhookLogs: "暂无 Webhook 发送记录",
    noWebhookLogsDesc: "首次付款后将显示日志",
    webhookNotConfigured: "未配置 Webhook",
    webhookActive: "Webhook 已启用",
    webhookSaved: "Webhook 已保存",
    webhookTested: "测试已发送",
    event: "事件",
    responseCode: "响应代码",
    responseTime: "响应时间",
    payload: "数据",
    delivered: "已送达",
    deliveryFailed: "发送失败",
    webhookGuide: "如何配置",
    webhookGuideDesc: "输入您的服务器地址和密钥。WestPay 将为每笔交易发送通知。",

    // Withdrawals panel
    withdrawalsTitle: "提现",
    withdrawalsDesc: "将资金提现到手机钱包",
    requestWithdrawal: "申请提现",
    withdrawalHistory: "提现记录",
    selectCountry: "选择国家",
    selectOperator: "选择运营商",
    enterPhone: "电话号码",
    enterAmount: "金额",
    availableBalance: "可用余额",
    withdrawalFees: "手续费",
    netAmount: "净额",
    withdrawalMode: "模式",
    autoMode: "自动",
    manualMode: "手动",
    adminNote: "管理员备注",
    omnipayRef: "Westpay 参考号",
    noWithdrawals: "暂无提现",
    noWithdrawalsDesc: "您的提现申请将显示在此处",
    totalWithdrawn: "已提现总额",
    pendingWithdrawals: "待处理",
    approvedWithdrawals: "已批准",
    fees: "手续费",
    reference: "参考号",

    // Wallet Transfers panel
    walletTransfersTitle: "余额转账",
    walletTransfersDesc: "在不同国家之间转移余额",
    newTransfer: "新转账",
    fromCountry: "来源国家",
    toCountry: "目标国家",
    transferAmount: "转账金额",
    transferFee: "转账手续费",
    netTransfer: "实际到账金额",
    confirmTransfer: "确认转账",
    transferHistory: "转账记录",
    noTransfers: "暂无转账",
    noTransfersDesc: "您的跨国转账将显示在此处",
    totalTransfers: "转账笔数",
    transferWarning: "转账将立即扣款。管理员必须批准后才能记入目标账户。",
    selectFromCountry: "选择来源国家",
    selectToCountry: "选择目标国家",

    // Settings panel
    settingsTitle: "设置",
    settingsDesc: "管理您的个人资料和偏好设置",
    profile: "个人资料",
    profileInfo: "个人信息",
    businessName: "企业名称",
    email: "邮箱",
    website: "网站",
    websitePlaceholder: "https://yoursite.com",
    securitySection: "安全",
    changePassword: "修改密码",
    currentPassword: "当前密码",
    newPassword: "新密码",
    confirmNewPassword: "确认新密码",
    passwordUpdated: "密码已更新",
    profileUpdated: "资料已更新",
    accountSection: "我的账户",
    logoutTitle: "退出登录",
    logoutDesc: "您将被重定向到登录页面",
    logoutBtn: "退出登录",
    dangerZone: "危险区域",
    languageSection: "仪表盘语言",

    // Payment Links panel
    paymentLinksTitle: "支付链接",
    paymentLinksDesc: "创建可共享的链接以接收付款",
    newLink: "新建链接",
    linkName: "链接名称",
    linkNamePlaceholder: "例如：订单付款",
    amountType: "金额类型",
    fixedAmount: "固定金额",
    flexibleAmount: "自由金额",
    amountCFA: "金额 (FCFA)",
    redirectUrl: "跳转链接",
    redirectUrlPlaceholder: "https://yoursite.com/thank-you",
    paymentLimit: "支付次数限制",
    paymentLimitPlaceholder: "不限",
    createLink: "创建链接",
    editLink: "编辑链接",
    saveLink: "保存",
    noLinks: "暂无支付链接",
    noLinksDesc: "创建您的第一个链接以开始接收付款",
    linksCreated: "已创建链接",
    paymentsReceived: "已收款笔数",
    totalRevenue: "总交易额",
    linkActive: "启用",
    linkInactive: "禁用",
    linkExpired: "已过期",
    limitReached: "已达上限",
    paymentsCount: "笔付款",
    received: "已收款",
    limit: "限制",
    openLink: "打开链接",
    deleteLink: "删除链接",
    createFirstLink: "创建链接",
    fixed: "固定",
    flexible: "自由",

    // Settings extra
    myProfile: "我的资料",
    merchant: "商户",
    statusActive: "启用",
    security: "安全",
    passwordChanged: "密码已修改",
    session: "会话",

    // Payment links extra
    linkCreated: "链接已创建",
    linkUpdated: "链接已更新",
    linkDeleted: "链接已删除",
    links: "链接",
    payments: "付款",
    volume: "交易额",
    yourLinks: "您的链接",
    expired: "已过期",
    unlimited: "不限",

    // Wallet panel
    walletTitle: "钱包余额",
    walletDesc: "按国家查看您的余额概览",
    totalConsolidatedBalance: "合并总余额",
    noCountriesConfigured: "未配置任何国家",
    countryDisabled: "国家已禁用",
    cryptoBalances: "加密货币余额",
    disabled: "已禁用",

    // Analyse panel
    analyseTitle: "数据分析",
    analyseDesc: "支付表现与统计数据",
    globalStats: "全局统计",
    successRate: "成功率",
    confirmedVolume: "已确认交易额",
    statusBreakdown: "状态分布",
    statusConfirmed: "已确认",
    statusPending: "待处理",
    statusFailed: "失败",
    last7daysVolume: "近7天交易额",
    performanceByCountry: "按国家显示表现",
    todayAndYesterday: "今天与昨天",
    transactionSingular: "笔交易",
    transactionPlural: "笔交易",
    confirmedLabel: "已确认",
    viewAll: "查看全部",
    recentTransactionsTitle: "最近交易",
    walletBalance: "钱包余额",
    successCount: "成功",
    noFeesLabel: "免手续费",
    sendMoney: "转账",
    processingLabel: "处理中…",
    insufficientFunds: "余额不足",
    pendingLabel: "待处理",
    confirmedLabel2: "已确认",
    failedLabel: "失败",

    // Public: language switcher
    chooseLanguage: "选择语言",

    // Public: payment page (payin)
    payTitle: "支付",
    payStep1: "支付方式",
    payStep2: "信息",
    payStep3: "确认",
    payChooseMethod: "选择您的支付方式",
    payMobileMoney: "移动支付 (Mobile Money)",
    payCrypto: "加密货币 (通过 OxaPay)",
    payAmountToPay: "应付金额",
    payMerchant: "商户",
    payCountry: "国家",
    payFullName: "姓名",
    payFullNamePlaceholder: "请输入您的姓名",
    payPhoneNumber: "电话号码",
    payPhoneNumberPlaceholder: "例如：90000000",
    payOperator: "运营商",
    payChooseOperator: "选择运营商",
    payPayNow: "立即支付",
    payProcessing: "处理中...",
    paySendingRequest: "正在发送支付请求...",
    payWaitingValidation: "等待您在手机上确认",
    payValidateOnPhone: "拨打您手机收到的 USSD 码以确认支付",
    payValidateOnLink: "点击收到的链接以确认支付",
    payOpenPaymentLink: "打开支付链接",
    paySuccess: "支付成功！",
    paySuccessDesc: "您的付款已成功确认",
    payFailed: "支付失败",
    payFailedDesc: "支付未能确认，请重试。",
    payExpired: "支付已过期",
    payExpiredDesc: "支付时限已过",
    payTryAgain: "重试",
    payBackToMerchant: "返回商户页面",
    via: "通过",
    time: "时间",
    payMethodRequired: "需要选择支付方式",
    payMethodRequiredDesc: "请选择一种支付方式",
    payNameRequired: "请输入姓名",
    payPhoneRequired: "请输入电话号码",
    payOperatorRequired: "请选择运营商",
    payInvalidPhone: "电话号码无效",
    payErrorTitle: "错误",
    payErrorGeneric: "发生错误，请重试。",
    payTransactionRef: "参考号",
    payDate: "日期",
    payLinkNotFound: "未找到支付链接",
    payLinkExpired: "该支付链接已过期",
    payLinkInactive: "该支付链接已禁用",
    payLinkLimitReached: "该支付链接已达到支付次数上限",
    payEnterAmount: "输入金额",
    payEnterAmountDesc: "此链接接受自由金额",
    payMerchantNotFound: "未找到商户",
    payContinue: "继续",
    payChangeLanguage: "切换语言",
    payHelp: "帮助",
    payInvalidLink: "链接无效",
    payInvalidAmount: "请输入有效金额",
    payChooseOperatorDesc: "选择一个运营商以继续",
    payPhoneNumberDesc: "您的号码",
    paySecurityRobotPay: "RobotPay 安全保护",
    payVerificationInProgress: "正在验证...",
    payWaitingConfirmation: "等待付款确认",
    payProcessingRequestBy: "您的请求正在处理中，由",
    payDoNotClosePage: "请勿关闭此页面",
    payRedirectionIn: "将在",
    payRedirectionSeconds: "秒后跳转至商户...",
    payRedirectionClickIfNo: "如果没有跳转，请点击此处",
    payCancel: "取消",
    payConfirmPayment: "确认付款",
    payOrangeMoneyBurkinaCote: "验证码",
    payOrangeMoneyBurkinaDesc: "对于布基纳法索 Orange Money，请拨打 *144*4*6*金额# 生成付款码，然后在下方输入。",
    payOrangeMoneyCoteDesc: "对于科特迪瓦 Orange Money，请拨打 #144*82# 生成付款码，然后在下方输入。",
    payOrangeMoneyEnterCode: "输入付款码",
    payCustomerSupport: "客户支持",
    payAnyQuestion: "有问题？付款需要帮助？",
    payYourName: "您的姓名",
    payYourWhatsApp: "您的 WhatsApp (含国家代码)",
    payDescribeProblem: "描述您的问题...",
    payMessageSent: "消息已发送！我们的团队将尽快与您联系。",
    paySendMessage: "发送消息",

    // Public: OTP modal
    otpTitle: "验证码",
    otpDesc: "验证码已发送至您的手机",
    otpEnterCode: "请输入收到的验证码",
    otpCodePlaceholder: "验证码",
    otpCodeRequired: "请输入验证码",
    otpInvalidCode: "验证码无效",
    otpVerify: "验证",
    otpVerifying: "验证中...",
    otpResend: "重新发送验证码",
    otpResendIn: "重新发送倒计时",
    otpResent: "验证码已重新发送",
    otpTimeExpired: "时间已过期，请重新开始",

    // Public: crypto payment page
    cryptoPayTitle: "加密货币支付",
    cryptoScanQr: "扫描二维码进行支付",
    cryptoWalletAddress: "钱包地址",
    cryptoAmountToSend: "应发送金额",
    cryptoCopyAddress: "复制地址",
    cryptoAddressCopied: "地址已复制",
    cryptoTimeRemaining: "剩余时间",
    cryptoWaitingPayment: "等待付款中...",
    cryptoConfirmed: "支付已确认",
    cryptoExpiredTitle: "会话已过期",
    cryptoExpiredDesc: "支付时限已过，请生成新的发票",
    cryptoNetwork: "网络",
    cryptoTrackId: "追踪编号",
    cryptoStatusWaiting: "等待支付",
    cryptoStatusConfirming: "确认中",
    cryptoStatusPaying: "支付已收到",
    cryptoStatusPaid: "支付已确认 ✓",
    cryptoStatusExpired: "链接已过期",
    cryptoStatusFailed: "支付失败",
    cryptoStatusRefunded: "已退款",
    cryptoStatusDetected: "检测到交易！",
    cryptoStatusConfirmingBlockchain: "区块链确认中…",
    cryptoPaidDesc: "您的交易已在区块链上确认。",
    cryptoTxHash: "交易哈希",
    cryptoWarning: "⚠️ 请务必在正确的网络上发送准确的金额。任何错误都可能导致资金永久丢失。",
    cryptoScanWallet: "使用您的加密钱包扫描",
    cryptoDepositAddress: "充值地址",
    cryptoSecurePayment: "安全支付",
    cryptoStepInfo: "信息",
    cryptoStepPayment: "支付",
    cryptoMerchant: "商户",
    cryptoPurpose: "支付目的",
    cryptoCurrency: "支付货币",
    cryptoAmountToPay: "应付金额",
    cryptoPayNow: "立即支付",
    cryptoPreparing: "正在准备支付…",
    cryptoExactAmount: "应发送的准确金额",
    cryptoLinkNotFound: "页面未找到",
    cryptoLinkInvalid: "此支付链接无效。",
    cryptoFreeAmount: "自由金额",
    cryptoStep: "步骤",
    cryptoOf: "/",

    // Public: API docs
    docsTitle: "API 文档",
    docsSubtitle: "将 WestPay 集成到您的应用程序中",
    docsIntro: "欢迎查看 WestPay API 文档",
    docsPinTitle: "受保护的访问",
    docsPinDesc: "请输入您的6位数 PIN 码以访问文档",
    docsPinPlaceholder: "6位数 PIN 码",
    docsAccess: "进入",
    docsInvalidPin: "PIN 码无效",
    docsGettingStarted: "快速开始",
    docsEndpoints: "接口列表",
    docsRequestBody: "请求体",
    docsResponse: "响应",
    docsParameters: "参数",
    docsRequired: "必填",
    docsRestricted: "限制使用",
    docsAccessTitle: "文档访问",
    docsAccessDesc: "输入您的商户凭据以访问 API 文档。",
    docsEmailLabel: "电子邮件地址",
    docsPinLabel: "PIN 码（6位数字）",
    docsShowPin: "显示 PIN",
    docsHidePin: "隐藏 PIN",
    docsSecurityCode: "安全码",
    docsCaptchaPlaceholder: "输入上方代码",
    docsCaptchaError: "验证码错误，已生成新代码。",
    docsVerifying: "验证中...",
    docsAccessBtn: "访问文档",
    docsSecuredAccess: "安全访问",
    docsPinConfigured: "您的 PIN 由管理员配置。每次访问都会被记录。",
    docsSecuredDocs: "安全文档",
    docsIntegrationTitle: "将 RobotPay 集成到您的应用程序中",
    docsIntegrationDesc: "访问我们针对西非和中非的 Mobile Money 支付 API 的完整文档。",
    docsFeature1: "完整的 RobotPay API 文档",
    docsFeature2: "即可集成的代码示例",
    docsFeature3: "按国家管理您的 API 密钥",
    docsFeature4: "通过个人 PIN 安全访问",
    cryptoDocsTitle: "加密货币 API 文档",
    cryptoDocsSubtitle: "RobotPay — 加密货币支付",
    cryptoDocsIntroTitle: "简介",
    cryptoDocsIntroSubtitle: "RobotPay 加密货币 API — 接受加密货币支付",
    cryptoDocsIntroDesc: "RobotPay 加密货币 API 允许您以简单安全的方式接受加密货币支付（USDT, BTC, ETH, LTC, TRX 等）。您的客户可以从任何国家使用加密货币支付，不受地理限制。",
    cryptoDocsGlobalTitle: "全球",
    cryptoDocsGlobalDesc: "来自任何国家的跨境支付",
    cryptoDocsInstantTitle: "即时",
    cryptoDocsInstantDesc: "通过我们的实时系统自动确认",
    cryptoDocsSecureTitle: "安全",
    cryptoDocsSecureDesc: "HMAC-SHA256 加密，不存储私钥",
    cryptoDocsFeesTitle: "服务费",
    cryptoDocsFeesDesc: "每笔收到的存款收取 5% · 每笔提现收取 5%",
    cryptoDocsSupportedTitle: "支持的加密货币",
    cryptoDocsCredentialsTitle: "我的凭据",
    cryptoDocsEnabled: "您的账户已启用加密货币支付",
    cryptoDocsDisabled: "加密货币支付未启用 — 请联系管理员",
    cryptoDocsSlugLabel: "您的 Slug（公开标识符）",
    cryptoDocsApiKeyLabel: "您的加密货币 API 密钥",
    cryptoDocsPaymentPageLabel: "支付 URL（您的页面）",
    cryptoDocsNoApiKey: "尚未生成 API 密钥 — 请前往您的仪表盘 → 加密货币 → API",
    cryptoDocsHowToUseApiKey: "如何使用 API 密钥",
    cryptoDocsAddHeader: "在每个受保护的 API 请求中添加以下标头：",
    cryptoDocsSlugTitle: "支付链接（无代码）",
    cryptoDocsSlugSubtitle: "简单的解决方案 — 无需调用 API 即可重定向您的客户",
    cryptoDocsSlugDesc: "最简单的方法：使用您的 slug 和支付参数构建一个 URL。RobotPay 会自动创建发票并向您的客户显示加密货币支付页面。",
    cryptoDocsUrlStructure: "URL 结构",
    cryptoDocsParameters: "参数",
    cryptoDocsParamName: "参数",
    cryptoDocsParamRequired: "必选",
    cryptoDocsParamDesc: "描述",
    cryptoDocsExamples: "具体示例",
    cryptoDocsHtmlButton: "集成到您网站的 HTML 按钮",
    cryptoDocsInvoiceTitle: "创建发票 (API)",
    cryptoDocsInvoiceSubtitle: "对于高级集成 — 从后端完全控制",
  },

  pt: {
    // Navigation
    overview: "Visão geral",
    transactions: "Transações",
    transfers: "Transferências",
    withdrawals: "Retiradas",
    paymentlinks: "Links de pagamento",
    apikeys: "Chaves API",
    webhook: "Webhook",
    settings: "Configurações",
    navigation: "Navegação",
    merchantSpace: "Espaço do Comerciante",
    notifications: "Notificações",
    messages: "Mensagens",
    help: "Ajuda",
    logout: "Sair",
    language: "Idioma",
    dashboard: "Painel",

    // Common
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Excluir",
    edit: "Editar",
    create: "Criar",
    add: "Adicionar",
    search: "Pesquisar",
    filter: "Filtrar",
    export: "Exportar",
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    noData: "Sem dados",
    actions: "Ações",
    status: "Estado",
    date: "Data",
    amount: "Montante",
    total: "Total",
    copy: "Copiar",
    copied: "Copiado!",
    active: "Ativo",
    inactive: "Inativo",
    activate: "Ativar",
    deactivate: "Desativar",
    all: "Todos",
    yes: "Sim",
    no: "Não",
    optional: "opcional",
    close: "Fechar",
    back: "Voltar",
    next: "Próximo",
    previous: "Anterior",
    submit: "Enviar",
    reset: "Redefinir",
    today: "Hoje",
    yesterday: "Ontem",
    allTime: "Todo período",
    refresh: "Atualizar",
    noTransactions: "Sem transações",

    // Status
    pending: "Pendente",
    approved: "Aprovado",
    rejected: "Rejeitado",
    confirmed: "Confirmado",
    failed: "Falhou",
    suspended: "Suspenso",
    completed: "Concluído",
    processing: "Processando",

    // Dashboard Overview
    balance: "Saldo",
    reversements: "Retiradas",
    todayStats: "Estatísticas diárias",
    balanceByCountry: "Saldo por país",
    totalVolume: "Volume total",
    transactionCount: "Transações",
    noCountriesActive: "Nenhum país ativo",
    supportContact: "Contato de suporte",
    welcomeBack: "Bem-vindo",
    accountBalance: "Saldo da conta",

    // Transactions panel
    transactionHistory: "Histórico de transações",
    searchTransactions: "Pesquisar por ID, telefone...",
    filterByStatus: "Filtrar por estado",
    filterByCountry: "Filtrar por país",
    filterByDate: "Filtrar por data",
    txId: "ID Transação",
    phone: "Telefone",
    payer: "Pagador",
    country: "País",
    operator: "Operador",
    source: "Fonte",
    noTransactionsFound: "Nenhuma transação encontrada",
    noTransactionsDesc: "Suas transações aparecerão aqui",
    confirmedTransactions: "Transações confirmadas",
    pendingTransactions: "Pendentes",
    exportCsv: "Exportar CSV",
    transactionDetails: "Detalhes da transação",
    apiPayment: "Pagamento API",
    paymentLink: "Link de pagamento",
    allStatuses: "Todos os estados",
    allCountries: "Todos os países",
    allPeriods: "Todos os períodos",
    last7days: "Últimos 7 dias",
    last30days: "Últimos 30 dias",
    thisMonth: "Este mês",
    summary: "Resumo",
    recentTransactions: "Transações recentes",

    // API Keys panel
    apiKeysTitle: "Chaves API",
    apiKeysDesc: "Gerencie suas chaves de acesso por país",
    yourApiKeys: "Suas chaves API",
    apiKey: "Chave API",
    copyKey: "Copiar chave",
    keyActive: "Chave ativa",
    keyInactive: "Chave inativa",
    noApiKeys: "Nenhuma chave API",
    noApiKeysDesc: "Contate seu administrador para obter uma chave API",
    integrationGuide: "Guia de integração",
    testPayment: "Testar um pagamento",
    copyCode: "Copiar código",
    apiDocumentation: "Documentação API",
    authentication: "Autenticação",
    createPayment: "Criar pagamento",
    checkStatus: "Verificar estado",
    webhookNotif: "Notificação webhook",
    example: "Exemplo",

    // Webhook panel
    webhookTitle: "Webhook",
    webhookDesc: "Configure notificações automáticas",
    webhookUrl: "URL Webhook",
    webhookSecret: "Segredo Webhook",
    webhookUrlPlaceholder: "https://seusite.com/webhook",
    webhookSecretPlaceholder: "Sua chave secreta",
    saveWebhook: "Salvar webhook",
    testWebhook: "Testar webhook",
    webhookLogs: "Histórico de envios",
    noWebhookLogs: "Nenhum envio webhook",
    noWebhookLogsDesc: "Os logs aparecerão após os primeiros pagamentos",
    webhookNotConfigured: "Nenhum webhook configurado",
    webhookActive: "Webhook ativo",
    webhookSaved: "Webhook salvo",
    webhookTested: "Teste enviado",
    event: "Evento",
    responseCode: "Código de resposta",
    responseTime: "Tempo de resposta",
    payload: "Dados",
    delivered: "Entregue",
    deliveryFailed: "Falha na entrega",
    webhookGuide: "Como configurar",
    webhookGuideDesc: "Insira a URL do seu servidor e o segredo. O WestPay enviará uma notificação para cada transação.",

    // Withdrawals panel
    withdrawalsTitle: "Retiradas",
    withdrawalsDesc: "Retire seus fundos para uma carteira móvel",
    requestWithdrawal: "Solicitar retirada",
    withdrawalHistory: "Histórico de retiradas",
    selectCountry: "Selecionar um país",
    selectOperator: "Selecionar um operador",
    enterPhone: "Número de telefone",
    enterAmount: "Montante",
    availableBalance: "Saldo disponível",
    withdrawalFees: "Taxas",
    netAmount: "Montante líquido",
    withdrawalMode: "Modo",
    autoMode: "Auto",
    manualMode: "Manual",
    adminNote: "Nota do admin",
    omnipayRef: "Ref. Westpay",
    noWithdrawals: "Nenhuma retirada",
    noWithdrawalsDesc: "Suas solicitações de retirada aparecerão aqui",
    totalWithdrawn: "Total retirado",
    pendingWithdrawals: "Pendentes",
    approvedWithdrawals: "Aprovados",
    fees: "Taxas",
    reference: "Referência",

    // Wallet Transfers panel
    walletTransfersTitle: "Transferências de saldo",
    walletTransfersDesc: "Transfira seu saldo entre países",
    newTransfer: "Nova transferência",
    fromCountry: "País de origem",
    toCountry: "País de destino",
    transferAmount: "Valor a transferir",
    transferFee: "Taxa de transferência",
    netTransfer: "Valor líquido recebido",
    confirmTransfer: "Confirmar transferência",
    transferHistory: "Histórico de transferências",
    noTransfers: "Nenhuma transferência",
    noTransfersDesc: "Suas transferências entre países aparecerão aqui",
    totalTransfers: "Transferências",
    transferWarning: "A transferência será debitada imediatamente. O administrador deve aprová-la para creditar a conta de destino.",
    selectFromCountry: "Selecionar país de origem",
    selectToCountry: "Selecionar país de destino",

    // Settings panel
    settingsTitle: "Configurações",
    settingsDesc: "Gerencie seu perfil e preferências",
    profile: "Perfil",
    profileInfo: "Informações do perfil",
    businessName: "Nome da empresa",
    email: "Email",
    website: "Site",
    websitePlaceholder: "https://seusite.com",
    securitySection: "Segurança",
    changePassword: "Alterar senha",
    currentPassword: "Senha atual",
    newPassword: "Nova senha",
    confirmNewPassword: "Confirmar nova senha",
    passwordUpdated: "Senha atualizada",
    profileUpdated: "Perfil atualizado",
    accountSection: "Minha conta",
    logoutTitle: "Sair",
    logoutDesc: "Você será redirecionado para a página de login",
    logoutBtn: "Sair da conta",
    dangerZone: "Zona de perigo",
    languageSection: "Idioma do painel",

    // Payment Links panel
    paymentLinksTitle: "Links de Pagamento",
    paymentLinksDesc: "Crie links compartilháveis para receber pagamentos",
    newLink: "Novo link",
    linkName: "Nome do link",
    linkNamePlaceholder: "Ex: Pagamento pedido",
    amountType: "Tipo de montante",
    fixedAmount: "Montante fixo",
    flexibleAmount: "Montante livre",
    amountCFA: "Montante (FCFA)",
    redirectUrl: "URL de redirecionamento",
    redirectUrlPlaceholder: "https://seusite.com/obrigado",
    paymentLimit: "Limite de pagamentos",
    paymentLimitPlaceholder: "Ilimitado",
    createLink: "Criar link",
    editLink: "Editar link",
    saveLink: "Salvar",
    noLinks: "Nenhum link de pagamento",
    noLinksDesc: "Crie seu primeiro link para começar a receber pagamentos",
    linksCreated: "Links criados",
    paymentsReceived: "Pagamentos recebidos",
    totalRevenue: "Volume total",
    linkActive: "Ativo",
    linkInactive: "Inativo",
    linkExpired: "Expirado",
    limitReached: "Limite atingido",
    paymentsCount: "pagamentos",
    received: "recebidos",
    limit: "Limite",
    openLink: "Abrir link",
    deleteLink: "Excluir link",
    createFirstLink: "Criar um link",
    fixed: "Fixo",
    flexible: "Livre",

    // Settings extra
    myProfile: "Meu perfil",
    merchant: "Comerciante",
    statusActive: "Ativo",
    security: "Segurança",
    passwordChanged: "Senha alterada",
    session: "Sessão",

    // Payment links extra
    linkCreated: "Link criado",
    linkUpdated: "Link atualizado",
    linkDeleted: "Link excluído",
    links: "Links",
    payments: "Pagamentos",
    volume: "Volume",
    yourLinks: "Seus links",
    expired: "Expirado",
    unlimited: "Ilimitado",

    // Wallet panel
    walletTitle: "Saldo Wallet",
    walletDesc: "Visão geral dos seus saldos por país",
    totalConsolidatedBalance: "Saldo total consolidado",
    noCountriesConfigured: "Nenhum país configurado",
    countryDisabled: "País desativado",
    cryptoBalances: "Saldos Cripto",
    disabled: "Desativado",

    // Analyse panel
    analyseTitle: "Análise",
    analyseDesc: "Desempenho e estatísticas dos seus pagamentos",
    globalStats: "Estatísticas globais",
    successRate: "Taxa de sucesso",
    confirmedVolume: "Volume confirmado",
    statusBreakdown: "Distribuição de estados",
    statusConfirmed: "Confirmadas",
    statusPending: "Pendentes",
    statusFailed: "Falhas",
    last7daysVolume: "Volume últimos 7 dias",
    performanceByCountry: "Desempenho por país",
    todayAndYesterday: "Hoje & ontem",
    transactionSingular: "transação",
    transactionPlural: "transações",
    confirmedLabel: "confirmadas",
    viewAll: "Ver tudo",
    recentTransactionsTitle: "Transações recentes",
    walletBalance: "Saldo wallet",
    successCount: "Sucesso",
    noFeesLabel: "Sem taxas",
    sendMoney: "Enviar dinheiro",
    processingLabel: "Processando…",
    insufficientFunds: "Saldo insuficiente",
    pendingLabel: "Pendente",
    confirmedLabel2: "Confirmado",
    failedLabel: "Falhou",

    // Public: language switcher
    chooseLanguage: "Escolher idioma",

    // Public: payment page (payin)
    payTitle: "Pagamento",
    payStep1: "Método",
    payStep2: "Detalhes",
    payStep3: "Confirmação",
    payChooseMethod: "Escolha seu método de pagamento",
    payMobileMoney: "Mobile Money",
    payCrypto: "Cripto (via OxaPay)",
    payAmountToPay: "Montante a pagar",
    payMerchant: "Comerciante",
    payCountry: "País",
    payFullName: "Nome completo",
    payFullNamePlaceholder: "Seu nome completo",
    payPhoneNumber: "Número de telefone",
    payPhoneNumberPlaceholder: "Ex: 90000000",
    payOperator: "Operador",
    payChooseOperator: "Escolha um operador",
    payPayNow: "Pagar agora",
    payProcessing: "Processando...",
    paySendingRequest: "Enviando solicitação de pagamento...",
    payWaitingValidation: "Aguardando validação no seu telefone",
    payValidateOnPhone: "Valide o pagamento discando o código USSD recebido no seu telefone",
    payValidateOnLink: "Clique no link recebido para validar seu pagamento",
    payOpenPaymentLink: "Abrir link de pagamento",
    paySuccess: "Pagamento efetuado com sucesso!",
    paySuccessDesc: "Seu pagamento foi confirmado com sucesso",
    payFailed: "Pagamento falhou",
    payFailedDesc: "O pagamento não pôde ser confirmado. Tente novamente.",
    payExpired: "Pagamento expirado",
    payExpiredDesc: "O prazo de pagamento expirou",
    payTryAgain: "Tentar novamente",
    payBackToMerchant: "Voltar para o comerciante",
    via: "via",
    time: "Hora",
    payMethodRequired: "Método obrigatório",
    payMethodRequiredDesc: "Por favor, escolha um método de pagamento",
    payNameRequired: "Nome necessário",
    payPhoneRequired: "Telefone necessário",
    payOperatorRequired: "Operador necessário",
    payInvalidPhone: "Número de telefone inválido",
    payErrorTitle: "Erro",
    payErrorGeneric: "Ocorreu um erro. Tente novamente.",
    payTransactionRef: "Referência",
    payDate: "Data",
    payLinkNotFound: "Link de pagamento não encontrado",
    payLinkExpired: "Este link de pagamento expirou",
    payLinkInactive: "Este link de pagamento está desativado",
    payLinkLimitReached: "Este link de pagamento atingiu seu limite de pagamentos",
    payEnterAmount: "Digite o montante",
    payEnterAmountDesc: "Este link aceita um montante livre",
    payMerchantNotFound: "Comerciante não encontrado",
    payContinue: "Continuar",
    payChangeLanguage: "Mudar idioma",
    payHelp: "Ajuda",
    payInvalidLink: "Link inválido",
    payInvalidAmount: "Por favor, insira um valor válido",
    payChooseOperatorDesc: "Selecione um operador para continuar",
    payPhoneNumberDesc: "Seu número",
    paySecurityRobotPay: "Segurança RobotPay",
    payVerificationInProgress: "Verificação em curso...",
    payWaitingConfirmation: "Pagamento aguardando confirmação",
    payProcessingRequestBy: "Processando seu pedido por",
    payDoNotClosePage: "Não feche esta página",
    payRedirectionIn: "Redirecionando para o comerciante em",
    payRedirectionSeconds: "segundos...",
    payRedirectionClickIfNo: "Clique aqui se não for redirecionado",
    payCancel: "Cancelar",
    payConfirmPayment: "Confirmar pagamento",
    payOrangeMoneyBurkinaCote: "Código de verificação",
    payOrangeMoneyBurkinaDesc: "Para Orange Money Burkina Faso, gere um código de pagamento discando *144*4*6*montant# e insira-o abaixo.",
    payOrangeMoneyCoteDesc: "Para Orange Money Costa do Marfim, gere um código de pagamento discando #144*82# e insira-o abaixo.",
    payOrangeMoneyEnterCode: "Insira o código de pagamento",
    payCustomerSupport: "Suporte ao Cliente",
    payAnyQuestion: "Alguma dúvida? Precisa de ajuda com seu pagamento?",
    payYourName: "Seu nome",
    payYourWhatsApp: "Seu WhatsApp (com código do país)",
    payDescribeProblem: "Descreva seu problema...",
    payMessageSent: "Mensagem enviada! Nossa equipe entrará em contato em breve.",
    paySendMessage: "Enviar mensagem",

    // Public: OTP modal
    otpTitle: "Código de verificação",
    otpDesc: "Um código de verificação foi enviado ao seu telefone",
    otpEnterCode: "Digite o código recebido",
    otpCodePlaceholder: "Código OTP",
    otpCodeRequired: "Código OTP necessário",
    otpInvalidCode: "Código OTP inválido",
    otpVerify: "Verificar",
    otpVerifying: "Verificando...",
    otpResend: "Reenviar código",
    otpResendIn: "Reenviar em",
    otpResent: "Código reenviado",
    otpTimeExpired: "O prazo expirou, comece novamente",

    // Public: crypto payment page
    cryptoPayTitle: "Pagamento Cripto",
    cryptoScanQr: "Escaneie o QR code para pagar",
    cryptoWalletAddress: "Endereço da carteira",
    cryptoAmountToSend: "Montante a enviar",
    cryptoCopyAddress: "Copiar endereço",
    cryptoAddressCopied: "Endereço copiado",
    cryptoTimeRemaining: "Tempo restante",
    cryptoWaitingPayment: "Aguardando pagamento...",
    cryptoConfirmed: "Pagamento confirmado",
    cryptoExpiredTitle: "Sessão expirada",
    cryptoExpiredDesc: "O prazo de pagamento expirou, gere uma nova fatura",
    cryptoNetwork: "Rede",
    cryptoTrackId: "ID de rastreamento",
    cryptoStatusWaiting: "Aguardando pagamento",
    cryptoStatusConfirming: "Confirmando",
    cryptoStatusPaying: "Pagamento recebido",
    cryptoStatusPaid: "Pagamento confirmado ✓",
    cryptoStatusExpired: "Link expirado",
    cryptoStatusFailed: "Pagamento falhou",
    cryptoStatusRefunded: "Reembolsado",
    cryptoStatusDetected: "Transação detectada !",
    cryptoStatusConfirmingBlockchain: "Confirmando na blockchain…",
    cryptoPaidDesc: "Sua transação foi confirmada na blockchain.",
    cryptoTxHash: "Hash da transação",
    cryptoWarning: "⚠️ Envie exatamente o valor indicado na rede correta. Qualquer erro pode resultar em perda permanente de fundos.",
    cryptoScanWallet: "Escaneie com sua carteira cripto",
    cryptoDepositAddress: "Endereço de depósito",
    cryptoSecurePayment: "Pagamento seguro",
    cryptoStepInfo: "Informações",
    cryptoStepPayment: "Pagamento",
    cryptoMerchant: "Comerciante",
    cryptoPurpose: "Objetivo do pagamento",
    cryptoCurrency: "Moeda de pagamento",
    cryptoAmountToPay: "Valor a pagar",
    cryptoPayNow: "Pagar agora",
    cryptoPreparing: "Preparando pagamento…",
    cryptoExactAmount: "Valor exato a enviar",
    cryptoLinkNotFound: "Página não encontrada",
    cryptoLinkInvalid: "Este link de pagamento não é válido.",
    cryptoFreeAmount: "Valor livre",
    cryptoStep: "Etapa",
    cryptoOf: "de",

    // Public: API docs
    docsTitle: "Documentação API",
    docsSubtitle: "Integre o WestPay à sua aplicação",
    docsIntro: "Bem-vindo à documentação da API WestPay",
    docsPinTitle: "Acesso protegido",
    docsPinDesc: "Digite seu PIN de 6 dígitos para acessar a documentação",
    docsPinPlaceholder: "PIN de 6 dígitos",
    docsAccess: "Acessar",
    docsInvalidPin: "PIN inválido",
    docsGettingStarted: "Começando",
    docsEndpoints: "Endpoints",
    docsRequestBody: "Corpo da requisição",
    docsResponse: "Resposta",
    docsParameters: "Parâmetros",
    docsRequired: "Obrigatório",
    docsRestricted: "Uso restrito",
    docsAccessTitle: "Acesso à Documentação",
    docsAccessDesc: "Insira suas credenciais de comerciante para acessar a documentação da API.",
    docsEmailLabel: "Endereço de e-mail",
    docsPinLabel: "Código PIN (6 dígitos)",
    docsShowPin: "Mostrar PIN",
    docsHidePin: "Ocultar PIN",
    docsSecurityCode: "Código de segurança",
    docsCaptchaPlaceholder: "Digite o código acima",
    docsCaptchaError: "Código incorreto, um novo código foi gerado.",
    docsVerifying: "Verificando...",
    docsAccessBtn: "Acessar documentação",
    docsSecuredAccess: "Acesso seguro",
    docsPinConfigured: "Seu PIN é configurado pelo administrador. Cada acesso é registrado.",
    docsSecuredDocs: "Documentação segura",
    docsIntegrationTitle: "Integre o RobotPay em suas aplicações",
    docsIntegrationDesc: "Acesse a documentação completa da nossa API de pagamento Mobile Money para a África Ocidental e Central.",
    docsFeature1: "Documentação completa da API RobotPay",
    docsFeature2: "Exemplos de código prontos para integrar",
    docsFeature3: "Gerencie suas chaves API por país",
    docsFeature4: "Acesso seguro via PIN pessoal",
    cryptoDocsTitle: "Documentação da API Crypto",
    cryptoDocsSubtitle: "RobotPay — Pagamentos em criptomoedas",
    cryptoDocsIntroTitle: "Introdução",
    cryptoDocsIntroSubtitle: "RobotPay Crypto API — Aceite pagamentos em criptomoedas",
    cryptoDocsIntroDesc: "A API RobotPay Crypto permite que você aceite pagamentos em criptomoedas (USDT, BTC, ETH, LTC, TRX e mais) de forma simples e segura. Seus clientes podem pagar em cripto de qualquer país, sem restrições geográficas.",
    cryptoDocsGlobalTitle: "Global",
    cryptoDocsGlobalDesc: "Pagamentos sem fronteiras de qualquer país",
    cryptoDocsInstantTitle: "Instantâneo",
    cryptoDocsInstantDesc: "Confirmações automáticas através do nosso sistema em tempo real",
    cryptoDocsSecureTitle: "Seguro",
    cryptoDocsSecureDesc: "Criptografia HMAC-SHA256, sem armazenamento de chaves privadas",
    cryptoDocsFeesTitle: "Taxas de serviço",
    cryptoDocsFeesDesc: "5% em cada depósito recebido · 5% em cada retirada efetuada",
    cryptoDocsSupportedTitle: "Criptomoedas suportadas",
    cryptoDocsCredentialsTitle: "Minhas credenciais",
    cryptoDocsEnabled: "Pagamentos em cripto ativados na sua conta",
    cryptoDocsDisabled: "Pagamentos em cripto não ativados — contate o administrador",
    cryptoDocsSlugLabel: "Seu slug (identificador público)",
    cryptoDocsApiKeyLabel: "Sua chave API crypto",
    cryptoDocsPaymentPageLabel: "URL de pagamento (sua página)",
    cryptoDocsNoApiKey: "Chave API ainda não gerada — vá ao seu painel → Crypto → API",
    cryptoDocsHowToUseApiKey: "Como usar a chave API",
    cryptoDocsAddHeader: "Adicione o seguinte cabeçalho a cada solicitação de API protegida:",
    cryptoDocsSlugTitle: "Link de pagamento (sem código)",
    cryptoDocsSlugSubtitle: "Solução simples — redirecione seus clientes sem chamar a API",
    cryptoDocsSlugDesc: "O método mais simples: construa uma URL com seu slug e os parâmetros de pagamento. O RobotPay cria automaticamente a fatura e exibe a página de pagamento cripto para o seu cliente.",
    cryptoDocsUrlStructure: "Estrutura da URL",
    cryptoDocsParameters: "Parâmetros",
    cryptoDocsParamName: "Parâmetro",
    cryptoDocsParamRequired: "Obrigatório",
    cryptoDocsParamDesc: "Descrição",
    cryptoDocsExamples: "Exemplos concretos",
    cryptoDocsHtmlButton: "Botão HTML para integrar no seu site",
    cryptoDocsInvoiceTitle: "Criar uma fatura (API)",
    cryptoDocsInvoiceSubtitle: "Para integrações avançadas — controle total a partir do seu backend",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  currentLanguage: { code: Lang; label: string; flag: string };
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function readStoredLang(): Lang | null {
  const saved = localStorage.getItem("westpay_lang");
  if (saved === "fr" || saved === "en" || saved === "pt" || saved === "zh") return saved;
  return null;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => readStoredLang() || "en");

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("westpay_lang", newLang);
    localStorage.setItem("westpay_lang_explicit", "1");
  };

  // Auto-detect language once from country (used by public pay pages) unless
  // the user has already explicitly picked a language before.
  const autoSetLangFromCountry = (country?: string | null) => {
    if (localStorage.getItem("westpay_lang_explicit") === "1") return;
    const detected = detectLangFromCountry(country);
    setLangState(detected);
    localStorage.setItem("westpay_lang", detected);
  };

  const autoSetLangFromBrowser = () => {
    if (localStorage.getItem("westpay_lang_explicit") === "1") return;
    const detected = detectLangFromBrowser();
    setLangState(detected);
    localStorage.setItem("westpay_lang", detected);
  };

  // Sets a default language without marking the choice as explicit, so
  // later auto-detection (by country/browser) can still override it.
  const setDefaultLang = (newLang: Lang) => {
    if (localStorage.getItem("westpay_lang_explicit") === "1") return;
    setLangState(newLang);
    localStorage.setItem("westpay_lang", newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || translations["en"][key] || translations["fr"][key] || key;
  };

  const currentLanguage = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, currentLanguage, autoSetLangFromCountry, autoSetLangFromBrowser, setDefaultLang } as any}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx as LanguageContextType & {
    autoSetLangFromCountry: (country?: string | null) => void;
    autoSetLangFromBrowser: () => void;
    setDefaultLang: (lang: Lang) => void;
  };
}
