import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "fr" | "en" | "pt";

export const LANGUAGES: { code: Lang; label: string; flag: string }[] = [
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
];

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Navigation
    overview: "Vue d'ensemble",
    transactions: "Transactions",
    transfers: "Virements",
    withdrawals: "Reversements",
    paymentlinks: "Liens de paiement",
    apikeys: "Clés API",
    webhook: "Webhook",
    settings: "Paramètres",
    navigation: "Navigation",
    merchantSpace: "Espace Marchand",
    notifications: "Notifications",
    messages: "Messages",
    help: "Aide",
    logout: "Déconnexion",
    language: "Langue",
    dashboard: "Tableau de bord",

    // Common
    save: "Enregistrer",
    cancel: "Annuler",
    confirm: "Confirmer",
    delete: "Supprimer",
    edit: "Modifier",
    create: "Créer",
    add: "Ajouter",
    search: "Rechercher",
    filter: "Filtrer",
    export: "Exporter",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    noData: "Aucune donnée",
    actions: "Actions",
    status: "Statut",
    date: "Date",
    amount: "Montant",
    total: "Total",
    copy: "Copier",
    copied: "Copié !",
    active: "Actif",
    inactive: "Inactif",
    activate: "Activer",
    deactivate: "Désactiver",
    all: "Tous",
    yes: "Oui",
    no: "Non",
    optional: "optionnel",
    close: "Fermer",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    submit: "Soumettre",
    reset: "Réinitialiser",
    today: "Aujourd'hui",
    yesterday: "Hier",
    allTime: "Tout",
    refresh: "Actualiser",
    noTransactions: "Aucune transaction",

    // Status
    pending: "En attente",
    approved: "Approuvé",
    rejected: "Rejeté",
    confirmed: "Confirmé",
    failed: "Échoué",
    suspended: "Suspendu",
    completed: "Terminé",
    processing: "En cours",

    // Dashboard Overview
    balance: "Solde",
    reversements: "Reversements",
    todayStats: "Statistique journalier",
    balanceByCountry: "Solde par pays",
    totalVolume: "Volume total",
    transactionCount: "Transactions",
    noCountriesActive: "Aucun pays actif",
    supportContact: "Contact support",
    welcomeBack: "Bienvenue",
    accountBalance: "Solde du compte",

    // Transactions panel
    transactionHistory: "Historique des transactions",
    searchTransactions: "Rechercher par ID, téléphone...",
    filterByStatus: "Filtrer par statut",
    filterByCountry: "Filtrer par pays",
    filterByDate: "Filtrer par date",
    txId: "ID Transaction",
    phone: "Téléphone",
    payer: "Payeur",
    country: "Pays",
    operator: "Opérateur",
    source: "Source",
    noTransactionsFound: "Aucune transaction trouvée",
    noTransactionsDesc: "Vos transactions apparaîtront ici",
    confirmedTransactions: "Transactions confirmées",
    pendingTransactions: "En attente",
    exportCsv: "Exporter CSV",
    transactionDetails: "Détails de la transaction",
    apiPayment: "API Payment",
    paymentLink: "Lien de paiement",
    allStatuses: "Tous les statuts",
    allCountries: "Tous les pays",
    allPeriods: "Toutes les périodes",
    last7days: "7 derniers jours",
    last30days: "30 derniers jours",
    thisMonth: "Ce mois",
    summary: "Résumé",
    recentTransactions: "Transactions récentes",

    // API Keys panel
    apiKeysTitle: "Clés API",
    apiKeysDesc: "Gérez vos clés d'accès par pays",
    yourApiKeys: "Vos clés API",
    apiKey: "Clé API",
    copyKey: "Copier la clé",
    keyActive: "Clé active",
    keyInactive: "Clé inactive",
    noApiKeys: "Aucune clé API",
    noApiKeysDesc: "Contactez votre administrateur pour obtenir une clé API",
    integrationGuide: "Guide d'intégration",
    testPayment: "Tester un paiement",
    copyCode: "Copier le code",
    apiDocumentation: "Documentation API",
    authentication: "Authentification",
    createPayment: "Créer un paiement",
    checkStatus: "Vérifier le statut",
    webhookNotif: "Notification webhook",
    example: "Exemple",

    // Webhook panel
    webhookTitle: "Webhook",
    webhookDesc: "Configurez les notifications automatiques",
    webhookUrl: "URL Webhook",
    webhookSecret: "Secret Webhook",
    webhookUrlPlaceholder: "https://votresite.com/webhook",
    webhookSecretPlaceholder: "Votre clé secrète",
    saveWebhook: "Enregistrer le webhook",
    testWebhook: "Tester le webhook",
    webhookLogs: "Historique des envois",
    noWebhookLogs: "Aucun envoi webhook",
    noWebhookLogsDesc: "Les logs apparaîtront après les premiers paiements",
    webhookNotConfigured: "Aucun webhook configuré",
    webhookActive: "Webhook actif",
    webhookSaved: "Webhook enregistré",
    webhookTested: "Test envoyé",
    event: "Événement",
    responseCode: "Code réponse",
    responseTime: "Temps réponse",
    payload: "Données",
    delivered: "Livré",
    deliveryFailed: "Échec de livraison",
    webhookGuide: "Comment configurer",
    webhookGuideDesc: "Entrez l'URL de votre serveur et le secret. WestPay enverra une notification à chaque transaction.",

    // Withdrawals panel
    withdrawalsTitle: "Reversements",
    withdrawalsDesc: "Retirez vos fonds vers un portefeuille mobile",
    requestWithdrawal: "Demander un reversement",
    withdrawalHistory: "Historique des reversements",
    selectCountry: "Sélectionner un pays",
    selectOperator: "Sélectionner un opérateur",
    enterPhone: "Numéro de téléphone",
    enterAmount: "Montant",
    availableBalance: "Solde disponible",
    withdrawalFees: "Frais",
    netAmount: "Montant net",
    withdrawalMode: "Mode",
    autoMode: "Auto",
    manualMode: "Manuel",
    adminNote: "Note admin",
    omnipayRef: "Réf. Westpay",
    noWithdrawals: "Aucun reversement",
    noWithdrawalsDesc: "Vos demandes de reversement apparaîtront ici",
    totalWithdrawn: "Total retiré",
    pendingWithdrawals: "En attente",
    approvedWithdrawals: "Approuvés",
    fees: "Frais",
    reference: "Référence",

    // Wallet Transfers panel
    walletTransfersTitle: "Virements de solde",
    walletTransfersDesc: "Transférez votre solde entre pays",
    newTransfer: "Nouveau virement",
    fromCountry: "Pays source",
    toCountry: "Pays destination",
    transferAmount: "Montant à transférer",
    transferFee: "Frais de transfert",
    netTransfer: "Montant net reçu",
    confirmTransfer: "Confirmer le virement",
    transferHistory: "Historique des virements",
    noTransfers: "Aucun virement",
    noTransfersDesc: "Vos virements entre pays apparaîtront ici",
    totalTransfers: "Virements",
    transferWarning: "Le virement sera débité immédiatement. L'administrateur doit l'approuver pour créditer le compte destination.",
    selectFromCountry: "Sélectionner le pays source",
    selectToCountry: "Sélectionner le pays destination",

    // Settings panel
    settingsTitle: "Paramètres",
    settingsDesc: "Gérez votre profil et vos préférences",
    profile: "Profil",
    profileInfo: "Informations du profil",
    businessName: "Nom de l'entreprise",
    email: "Email",
    website: "Site web",
    websitePlaceholder: "https://votresite.com",
    securitySection: "Sécurité",
    changePassword: "Changer le mot de passe",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    passwordUpdated: "Mot de passe mis à jour",
    profileUpdated: "Profil mis à jour",
    accountSection: "Mon compte",
    logoutTitle: "Déconnexion",
    logoutDesc: "Vous serez redirigé vers la page de connexion",
    logoutBtn: "Se déconnecter",
    dangerZone: "Zone dangereuse",
    languageSection: "Langue du dashboard",

    // Payment Links panel
    paymentLinksTitle: "Liens de Paiement",
    paymentLinksDesc: "Créez des liens partageables pour recevoir des paiements",
    newLink: "Nouveau lien",
    linkName: "Nom du lien",
    linkNamePlaceholder: "Ex: Paiement commande",
    amountType: "Type de montant",
    fixedAmount: "Montant fixe",
    flexibleAmount: "Montant libre",
    amountCFA: "Montant (F CFA)",
    redirectUrl: "URL de redirection",
    redirectUrlPlaceholder: "https://votresite.com/merci",
    paymentLimit: "Limite de paiements",
    paymentLimitPlaceholder: "Illimité",
    createLink: "Créer le lien",
    editLink: "Modifier le lien",
    saveLink: "Enregistrer",
    noLinks: "Aucun lien de paiement",
    noLinksDesc: "Créez votre premier lien pour recevoir des paiements",
    linksCreated: "Liens créés",
    paymentsReceived: "Paiements reçus",
    totalRevenue: "Volume total",
    linkActive: "Actif",
    linkInactive: "Inactif",
    linkExpired: "Expiré",
    limitReached: "Limite atteinte",
    paymentsCount: "paiements",
    received: "reçus",
    limit: "Limite",
    openLink: "Ouvrir le lien",
    deleteLink: "Supprimer le lien",
    createFirstLink: "Créer un lien",
    fixed: "Fixe",
    flexible: "Libre",

    // Settings extra
    myProfile: "Mon profil",
    merchant: "Marchand",
    statusActive: "Actif",
    security: "Sécurité",
    passwordChanged: "Mot de passe modifié",
    session: "Session",

    // Payment links extra
    linkCreated: "Lien créé",
    linkUpdated: "Lien mis à jour",
    linkDeleted: "Lien supprimé",
    links: "Liens",
    payments: "Paiements",
    volume: "Volume",
    yourLinks: "Vos liens",
    expired: "Expiré",
    unlimited: "Illimité",

    // Wallet panel
    walletTitle: "Solde Wallet",
    walletDesc: "Vue d'ensemble de vos soldes par pays",
    totalConsolidatedBalance: "Solde total consolidé",
    noCountriesConfigured: "Aucun pays configuré",
    countryDisabled: "Pays désactivé",
    cryptoBalances: "Soldes Crypto",
    disabled: "Désactivé",

    // Analyse panel
    analyseTitle: "Analyse",
    analyseDesc: "Performance et statistiques de vos paiements",
    globalStats: "Statistiques globales",
    successRate: "Taux succès",
    confirmedVolume: "Volume confirmé",
    statusBreakdown: "Répartition des statuts",
    statusConfirmed: "Confirmées",
    statusPending: "En attente",
    statusFailed: "Échouées",
    last7daysVolume: "Volume 7 derniers jours",
    performanceByCountry: "Performance par pays",
    todayAndYesterday: "Aujourd'hui & hier",
    transactionSingular: "transaction",
    transactionPlural: "transactions",
    confirmedLabel: "confirmées",
  },

  en: {
    // Navigation
    overview: "Overview",
    transactions: "Transactions",
    transfers: "Transfers",
    withdrawals: "Withdrawals",
    paymentlinks: "Payment Links",
    apikeys: "API Keys",
    webhook: "Webhook",
    settings: "Settings",
    navigation: "Navigation",
    merchantSpace: "Merchant Space",
    notifications: "Notifications",
    messages: "Messages",
    help: "Help",
    logout: "Logout",
    language: "Language",
    dashboard: "Dashboard",

    // Common
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    add: "Add",
    search: "Search",
    filter: "Filter",
    export: "Export",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    noData: "No data",
    actions: "Actions",
    status: "Status",
    date: "Date",
    amount: "Amount",
    total: "Total",
    copy: "Copy",
    copied: "Copied!",
    active: "Active",
    inactive: "Inactive",
    activate: "Activate",
    deactivate: "Deactivate",
    all: "All",
    yes: "Yes",
    no: "No",
    optional: "optional",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    reset: "Reset",
    today: "Today",
    yesterday: "Yesterday",
    allTime: "All time",
    refresh: "Refresh",
    noTransactions: "No transactions",

    // Status
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    confirmed: "Confirmed",
    failed: "Failed",
    suspended: "Suspended",
    completed: "Completed",
    processing: "Processing",

    // Dashboard Overview
    balance: "Balance",
    reversements: "Withdrawals",
    todayStats: "Daily Statistics",
    balanceByCountry: "Balance by Country",
    totalVolume: "Total volume",
    transactionCount: "Transactions",
    noCountriesActive: "No active countries",
    supportContact: "Support contact",
    welcomeBack: "Welcome back",
    accountBalance: "Account balance",

    // Transactions panel
    transactionHistory: "Transaction history",
    searchTransactions: "Search by ID, phone...",
    filterByStatus: "Filter by status",
    filterByCountry: "Filter by country",
    filterByDate: "Filter by date",
    txId: "Transaction ID",
    phone: "Phone",
    payer: "Payer",
    country: "Country",
    operator: "Operator",
    source: "Source",
    noTransactionsFound: "No transactions found",
    noTransactionsDesc: "Your transactions will appear here",
    confirmedTransactions: "Confirmed transactions",
    pendingTransactions: "Pending",
    exportCsv: "Export CSV",
    transactionDetails: "Transaction details",
    apiPayment: "API Payment",
    paymentLink: "Payment Link",
    allStatuses: "All statuses",
    allCountries: "All countries",
    allPeriods: "All periods",
    last7days: "Last 7 days",
    last30days: "Last 30 days",
    thisMonth: "This month",
    summary: "Summary",
    recentTransactions: "Recent transactions",

    // API Keys panel
    apiKeysTitle: "API Keys",
    apiKeysDesc: "Manage your access keys by country",
    yourApiKeys: "Your API keys",
    apiKey: "API Key",
    copyKey: "Copy key",
    keyActive: "Active key",
    keyInactive: "Inactive key",
    noApiKeys: "No API keys",
    noApiKeysDesc: "Contact your administrator to get an API key",
    integrationGuide: "Integration guide",
    testPayment: "Test a payment",
    copyCode: "Copy code",
    apiDocumentation: "API Documentation",
    authentication: "Authentication",
    createPayment: "Create payment",
    checkStatus: "Check status",
    webhookNotif: "Webhook notification",
    example: "Example",

    // Webhook panel
    webhookTitle: "Webhook",
    webhookDesc: "Configure automatic notifications",
    webhookUrl: "Webhook URL",
    webhookSecret: "Webhook Secret",
    webhookUrlPlaceholder: "https://yoursite.com/webhook",
    webhookSecretPlaceholder: "Your secret key",
    saveWebhook: "Save webhook",
    testWebhook: "Test webhook",
    webhookLogs: "Delivery history",
    noWebhookLogs: "No webhook deliveries",
    noWebhookLogsDesc: "Logs will appear after the first payments",
    webhookNotConfigured: "No webhook configured",
    webhookActive: "Webhook active",
    webhookSaved: "Webhook saved",
    webhookTested: "Test sent",
    event: "Event",
    responseCode: "Response code",
    responseTime: "Response time",
    payload: "Payload",
    delivered: "Delivered",
    deliveryFailed: "Delivery failed",
    webhookGuide: "How to configure",
    webhookGuideDesc: "Enter your server URL and secret. WestPay will send a notification for each transaction.",

    // Withdrawals panel
    withdrawalsTitle: "Withdrawals",
    withdrawalsDesc: "Withdraw your funds to a mobile wallet",
    requestWithdrawal: "Request withdrawal",
    withdrawalHistory: "Withdrawal history",
    selectCountry: "Select a country",
    selectOperator: "Select an operator",
    enterPhone: "Phone number",
    enterAmount: "Amount",
    availableBalance: "Available balance",
    withdrawalFees: "Fees",
    netAmount: "Net amount",
    withdrawalMode: "Mode",
    autoMode: "Auto",
    manualMode: "Manual",
    adminNote: "Admin note",
    omnipayRef: "Westpay Ref.",
    noWithdrawals: "No withdrawals",
    noWithdrawalsDesc: "Your withdrawal requests will appear here",
    totalWithdrawn: "Total withdrawn",
    pendingWithdrawals: "Pending",
    approvedWithdrawals: "Approved",
    fees: "Fees",
    reference: "Reference",

    // Wallet Transfers panel
    walletTransfersTitle: "Balance Transfers",
    walletTransfersDesc: "Transfer your balance between countries",
    newTransfer: "New transfer",
    fromCountry: "Source country",
    toCountry: "Destination country",
    transferAmount: "Transfer amount",
    transferFee: "Transfer fee",
    netTransfer: "Net amount received",
    confirmTransfer: "Confirm transfer",
    transferHistory: "Transfer history",
    noTransfers: "No transfers",
    noTransfersDesc: "Your country-to-country transfers will appear here",
    totalTransfers: "Transfers",
    transferWarning: "The transfer will be debited immediately. The administrator must approve it to credit the destination account.",
    selectFromCountry: "Select source country",
    selectToCountry: "Select destination country",

    // Settings panel
    settingsTitle: "Settings",
    settingsDesc: "Manage your profile and preferences",
    profile: "Profile",
    profileInfo: "Profile information",
    businessName: "Business name",
    email: "Email",
    website: "Website",
    websitePlaceholder: "https://yoursite.com",
    securitySection: "Security",
    changePassword: "Change password",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Confirm new password",
    passwordUpdated: "Password updated",
    profileUpdated: "Profile updated",
    accountSection: "My account",
    logoutTitle: "Logout",
    logoutDesc: "You will be redirected to the login page",
    logoutBtn: "Sign out",
    dangerZone: "Danger zone",
    languageSection: "Dashboard language",

    // Payment Links panel
    paymentLinksTitle: "Payment Links",
    paymentLinksDesc: "Create shareable links to receive payments",
    newLink: "New link",
    linkName: "Link name",
    linkNamePlaceholder: "Ex: Order payment",
    amountType: "Amount type",
    fixedAmount: "Fixed amount",
    flexibleAmount: "Flexible amount",
    amountCFA: "Amount (FCFA)",
    redirectUrl: "Redirect URL",
    redirectUrlPlaceholder: "https://yoursite.com/thank-you",
    paymentLimit: "Payment limit",
    paymentLimitPlaceholder: "Unlimited",
    createLink: "Create link",
    editLink: "Edit link",
    saveLink: "Save",
    noLinks: "No payment links",
    noLinksDesc: "Create your first link to start receiving payments",
    linksCreated: "Links created",
    paymentsReceived: "Payments received",
    totalRevenue: "Total volume",
    linkActive: "Active",
    linkInactive: "Inactive",
    linkExpired: "Expired",
    limitReached: "Limit reached",
    paymentsCount: "payments",
    received: "received",
    limit: "Limit",
    openLink: "Open link",
    deleteLink: "Delete link",
    createFirstLink: "Create a link",
    fixed: "Fixed",
    flexible: "Flexible",

    // Settings extra
    myProfile: "My profile",
    merchant: "Merchant",
    statusActive: "Active",
    security: "Security",
    passwordChanged: "Password changed",
    session: "Session",

    // Payment links extra
    linkCreated: "Link created",
    linkUpdated: "Link updated",
    linkDeleted: "Link deleted",
    links: "Links",
    payments: "Payments",
    volume: "Volume",
    yourLinks: "Your links",
    expired: "Expired",
    unlimited: "Unlimited",

    // Wallet panel
    walletTitle: "Wallet Balance",
    walletDesc: "Overview of your balances by country",
    totalConsolidatedBalance: "Total consolidated balance",
    noCountriesConfigured: "No countries configured",
    countryDisabled: "Country disabled",
    cryptoBalances: "Crypto Balances",
    disabled: "Disabled",

    // Analyse panel
    analyseTitle: "Analytics",
    analyseDesc: "Payment performance and statistics",
    globalStats: "Global statistics",
    successRate: "Success rate",
    confirmedVolume: "Confirmed volume",
    statusBreakdown: "Status breakdown",
    statusConfirmed: "Confirmed",
    statusPending: "Pending",
    statusFailed: "Failed",
    last7daysVolume: "Volume over last 7 days",
    performanceByCountry: "Performance by country",
    todayAndYesterday: "Today & yesterday",
    transactionSingular: "transaction",
    transactionPlural: "transactions",
    confirmedLabel: "confirmed",
  },

  pt: {
    // Navigation
    overview: "Visão geral",
    transactions: "Transações",
    transfers: "Transferências",
    withdrawals: "Retiradas",
    paymentlinks: "Links de pagamento",
    apikeys: "Chaves API",
    webhook: "Webhook",
    settings: "Configurações",
    navigation: "Navegação",
    merchantSpace: "Espaço do Comerciante",
    notifications: "Notificações",
    messages: "Mensagens",
    help: "Ajuda",
    logout: "Sair",
    language: "Idioma",
    dashboard: "Painel",

    // Common
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Excluir",
    edit: "Editar",
    create: "Criar",
    add: "Adicionar",
    search: "Pesquisar",
    filter: "Filtrar",
    export: "Exportar",
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    noData: "Sem dados",
    actions: "Ações",
    status: "Estado",
    date: "Data",
    amount: "Montante",
    total: "Total",
    copy: "Copiar",
    copied: "Copiado!",
    active: "Ativo",
    inactive: "Inativo",
    activate: "Ativar",
    deactivate: "Desativar",
    all: "Todos",
    yes: "Sim",
    no: "Não",
    optional: "opcional",
    close: "Fechar",
    back: "Voltar",
    next: "Próximo",
    previous: "Anterior",
    submit: "Enviar",
    reset: "Redefinir",
    today: "Hoje",
    yesterday: "Ontem",
    allTime: "Todo período",
    refresh: "Atualizar",
    noTransactions: "Sem transações",

    // Status
    pending: "Pendente",
    approved: "Aprovado",
    rejected: "Rejeitado",
    confirmed: "Confirmado",
    failed: "Falhou",
    suspended: "Suspenso",
    completed: "Concluído",
    processing: "Processando",

    // Dashboard Overview
    balance: "Saldo",
    reversements: "Retiradas",
    todayStats: "Estatísticas diárias",
    balanceByCountry: "Saldo por país",
    totalVolume: "Volume total",
    transactionCount: "Transações",
    noCountriesActive: "Nenhum país ativo",
    supportContact: "Contato de suporte",
    welcomeBack: "Bem-vindo",
    accountBalance: "Saldo da conta",

    // Transactions panel
    transactionHistory: "Histórico de transações",
    searchTransactions: "Pesquisar por ID, telefone...",
    filterByStatus: "Filtrar por estado",
    filterByCountry: "Filtrar por país",
    filterByDate: "Filtrar por data",
    txId: "ID Transação",
    phone: "Telefone",
    payer: "Pagador",
    country: "País",
    operator: "Operador",
    source: "Fonte",
    noTransactionsFound: "Nenhuma transação encontrada",
    noTransactionsDesc: "Suas transações aparecerão aqui",
    confirmedTransactions: "Transações confirmadas",
    pendingTransactions: "Pendentes",
    exportCsv: "Exportar CSV",
    transactionDetails: "Detalhes da transação",
    apiPayment: "Pagamento API",
    paymentLink: "Link de pagamento",
    allStatuses: "Todos os estados",
    allCountries: "Todos os países",
    allPeriods: "Todos os períodos",
    last7days: "Últimos 7 dias",
    last30days: "Últimos 30 dias",
    thisMonth: "Este mês",
    summary: "Resumo",
    recentTransactions: "Transações recentes",

    // API Keys panel
    apiKeysTitle: "Chaves API",
    apiKeysDesc: "Gerencie suas chaves de acesso por país",
    yourApiKeys: "Suas chaves API",
    apiKey: "Chave API",
    copyKey: "Copiar chave",
    keyActive: "Chave ativa",
    keyInactive: "Chave inativa",
    noApiKeys: "Nenhuma chave API",
    noApiKeysDesc: "Contate seu administrador para obter uma chave API",
    integrationGuide: "Guia de integração",
    testPayment: "Testar um pagamento",
    copyCode: "Copiar código",
    apiDocumentation: "Documentação API",
    authentication: "Autenticação",
    createPayment: "Criar pagamento",
    checkStatus: "Verificar estado",
    webhookNotif: "Notificação webhook",
    example: "Exemplo",

    // Webhook panel
    webhookTitle: "Webhook",
    webhookDesc: "Configure notificações automáticas",
    webhookUrl: "URL Webhook",
    webhookSecret: "Segredo Webhook",
    webhookUrlPlaceholder: "https://seusite.com/webhook",
    webhookSecretPlaceholder: "Sua chave secreta",
    saveWebhook: "Salvar webhook",
    testWebhook: "Testar webhook",
    webhookLogs: "Histórico de envios",
    noWebhookLogs: "Nenhum envio webhook",
    noWebhookLogsDesc: "Os logs aparecerão após os primeiros pagamentos",
    webhookNotConfigured: "Nenhum webhook configurado",
    webhookActive: "Webhook ativo",
    webhookSaved: "Webhook salvo",
    webhookTested: "Teste enviado",
    event: "Evento",
    responseCode: "Código de resposta",
    responseTime: "Tempo de resposta",
    payload: "Dados",
    delivered: "Entregue",
    deliveryFailed: "Falha na entrega",
    webhookGuide: "Como configurar",
    webhookGuideDesc: "Insira a URL do seu servidor e o segredo. O WestPay enviará uma notificação para cada transação.",

    // Withdrawals panel
    withdrawalsTitle: "Retiradas",
    withdrawalsDesc: "Retire seus fundos para uma carteira móvel",
    requestWithdrawal: "Solicitar retirada",
    withdrawalHistory: "Histórico de retiradas",
    selectCountry: "Selecionar um país",
    selectOperator: "Selecionar um operador",
    enterPhone: "Número de telefone",
    enterAmount: "Montante",
    availableBalance: "Saldo disponível",
    withdrawalFees: "Taxas",
    netAmount: "Montante líquido",
    withdrawalMode: "Modo",
    autoMode: "Auto",
    manualMode: "Manual",
    adminNote: "Nota do admin",
    omnipayRef: "Ref. Westpay",
    noWithdrawals: "Nenhuma retirada",
    noWithdrawalsDesc: "Suas solicitações de retirada aparecerão aqui",
    totalWithdrawn: "Total retirado",
    pendingWithdrawals: "Pendentes",
    approvedWithdrawals: "Aprovados",
    fees: "Taxas",
    reference: "Referência",

    // Wallet Transfers panel
    walletTransfersTitle: "Transferências de saldo",
    walletTransfersDesc: "Transfira seu saldo entre países",
    newTransfer: "Nova transferência",
    fromCountry: "País de origem",
    toCountry: "País de destino",
    transferAmount: "Valor a transferir",
    transferFee: "Taxa de transferência",
    netTransfer: "Valor líquido recebido",
    confirmTransfer: "Confirmar transferência",
    transferHistory: "Histórico de transferências",
    noTransfers: "Nenhuma transferência",
    noTransfersDesc: "Suas transferências entre países aparecerão aqui",
    totalTransfers: "Transferências",
    transferWarning: "A transferência será debitada imediatamente. O administrador deve aprová-la para creditar a conta de destino.",
    selectFromCountry: "Selecionar país de origem",
    selectToCountry: "Selecionar país de destino",

    // Settings panel
    settingsTitle: "Configurações",
    settingsDesc: "Gerencie seu perfil e preferências",
    profile: "Perfil",
    profileInfo: "Informações do perfil",
    businessName: "Nome da empresa",
    email: "Email",
    website: "Site",
    websitePlaceholder: "https://seusite.com",
    securitySection: "Segurança",
    changePassword: "Alterar senha",
    currentPassword: "Senha atual",
    newPassword: "Nova senha",
    confirmNewPassword: "Confirmar nova senha",
    passwordUpdated: "Senha atualizada",
    profileUpdated: "Perfil atualizado",
    accountSection: "Minha conta",
    logoutTitle: "Sair",
    logoutDesc: "Você será redirecionado para a página de login",
    logoutBtn: "Sair da conta",
    dangerZone: "Zona de perigo",
    languageSection: "Idioma do painel",

    // Payment Links panel
    paymentLinksTitle: "Links de Pagamento",
    paymentLinksDesc: "Crie links compartilháveis para receber pagamentos",
    newLink: "Novo link",
    linkName: "Nome do link",
    linkNamePlaceholder: "Ex: Pagamento pedido",
    amountType: "Tipo de montante",
    fixedAmount: "Montante fixo",
    flexibleAmount: "Montante livre",
    amountCFA: "Montante (FCFA)",
    redirectUrl: "URL de redirecionamento",
    redirectUrlPlaceholder: "https://seusite.com/obrigado",
    paymentLimit: "Limite de pagamentos",
    paymentLimitPlaceholder: "Ilimitado",
    createLink: "Criar link",
    editLink: "Editar link",
    saveLink: "Salvar",
    noLinks: "Nenhum link de pagamento",
    noLinksDesc: "Crie seu primeiro link para começar a receber pagamentos",
    linksCreated: "Links criados",
    paymentsReceived: "Pagamentos recebidos",
    totalRevenue: "Volume total",
    linkActive: "Ativo",
    linkInactive: "Inativo",
    linkExpired: "Expirado",
    limitReached: "Limite atingido",
    paymentsCount: "pagamentos",
    received: "recebidos",
    limit: "Limite",
    openLink: "Abrir link",
    deleteLink: "Excluir link",
    createFirstLink: "Criar um link",
    fixed: "Fixo",
    flexible: "Livre",

    // Settings extra
    myProfile: "Meu perfil",
    merchant: "Comerciante",
    statusActive: "Ativo",
    security: "Segurança",
    passwordChanged: "Senha alterada",
    session: "Sessão",

    // Payment links extra
    linkCreated: "Link criado",
    linkUpdated: "Link atualizado",
    linkDeleted: "Link excluído",
    links: "Links",
    payments: "Pagamentos",
    volume: "Volume",
    yourLinks: "Seus links",
    expired: "Expirado",
    unlimited: "Ilimitado",

    // Wallet panel
    walletTitle: "Saldo Wallet",
    walletDesc: "Visão geral dos seus saldos por país",
    totalConsolidatedBalance: "Saldo total consolidado",
    noCountriesConfigured: "Nenhum país configurado",
    countryDisabled: "País desativado",
    cryptoBalances: "Saldos Cripto",
    disabled: "Desativado",

    // Analyse panel
    analyseTitle: "Análise",
    analyseDesc: "Desempenho e estatísticas dos seus pagamentos",
    globalStats: "Estatísticas globais",
    successRate: "Taxa de sucesso",
    confirmedVolume: "Volume confirmado",
    statusBreakdown: "Distribuição de estados",
    statusConfirmed: "Confirmadas",
    statusPending: "Pendentes",
    statusFailed: "Falhas",
    last7daysVolume: "Volume últimos 7 dias",
    performanceByCountry: "Desempenho por país",
    todayAndYesterday: "Hoje & ontem",
    transactionSingular: "transação",
    transactionPlural: "transações",
    confirmedLabel: "confirmadas",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  currentLanguage: { code: Lang; label: string; flag: string };
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("westpay_lang");
    if (saved === "fr" || saved === "en" || saved === "pt") return saved;
    return "en";
  });

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("westpay_lang", newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || translations["fr"][key] || key;
  };

  const currentLanguage = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
