/**
 * Automatic status reconciliation for the active payment connectors.
 *
 * Only rows created by the current provider flows are eligible here.  In
 * particular, a legacy row which was assigned a new gateway during startup
 * migration is not enough to make it eligible for polling: its reference
 * must also have the prefix generated by that gateway.
 */
import { storage } from "./storage";
import { financialPool } from "./db";
import { getTransactionStatus as mbiyoGetStatus } from "./mbiyo";
import { clapayGetTransactionStatus } from "./clapay";
import {
  getLipaPapTransactionStatus,
  getLipaPapPayoutStatus,
  type LipaPapConfig,
} from "./lipapap";
import {
  notifyAdminPayment,
  notifyAdminWithdrawal,
  notifyMerchantPayment,
  notifyMerchantWithdrawal,
} from "./telegram-bot";
import { resolveProviderCode } from "@shared/provider-labels";
import { calcMerchantCredit as calcCredit } from "./feeConfig";

const PAYMENT_SUCCESS = new Set([
  "success", "successful", "completed", "complete", "paid", "approved",
  "confirmed", "settled",
]);
const PAYMENT_FAILURE = new Set([
  "failed", "failure", "cancelled", "canceled", "rejected", "declined",
  "error", "expired", "refund", "refunded", "reversal", "void",
]);
const WITHDRAWAL_SUCCESS = new Set([
  "completed", "success", "successful", "approved", "paid", "sent",
  "transferred", "processed", "delivered", "confirmed", "done", "ok",
]);
const WITHDRAWAL_FAILURE = new Set([
  "failed", "failure", "cancelled", "canceled", "rejected", "declined",
  "error",
]);

async function getConfiguredKey(envName: string, settingName: string): Promise<string | undefined> {
  return process.env[envName] || await storage.getSetting(settingName);
}

async function getMbiyoKey(): Promise<string | undefined> {
  return getConfiguredKey("MBIYO_API_KEY", "mbiyo_api_key");
}

async function getClapayKey(): Promise<string | undefined> {
  return getConfiguredKey("CLAPAY_API_KEY", "clapay_api_key");
}

async function getLipaPapConfig(): Promise<LipaPapConfig | undefined> {
  const [clientKey, secretKey, paymentUrl, callbackUrl, payerEmail, payoutCodesJson, environment] =
    await Promise.all([
      getConfiguredKey("LIPAPAP_CLIENT_KEY", "lipapap_client_key"),
      getConfiguredKey("LIPAPAP_SECRET_KEY", "lipapap_secret_key"),
      getConfiguredKey("LIPAPAP_PAYMENT_URL", "lipapap_payment_url"),
      storage.getSetting("lipapap_callback_url"),
      getConfiguredKey("LIPAPAP_PAYER_EMAIL", "lipapap_payer_email"),
      storage.getSetting("lipapap_payout_codes"),
      storage.getSetting("lipapap_environment"),
    ]);
  if (!clientKey || !secretKey || !paymentUrl) return undefined;

  let payoutProviderCodes: Record<string, Record<string, string>> = {};
  if (payoutCodesJson) {
    try {
      const parsed: unknown = JSON.parse(payoutCodesJson);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        payoutProviderCodes = Object.fromEntries(
          Object.entries(parsed).map(([country, operators]) => [
            country,
            operators && typeof operators === "object" && !Array.isArray(operators)
              ? Object.fromEntries(
                Object.entries(operators)
                  .filter((entry): entry is [string, string] =>
                    typeof entry[1] === "string" && entry[1].trim() !== "")
                  .map(([operator, code]) => [
                    operator.toLowerCase().replace(/[\s\-_]+/g, ""),
                    code.trim(),
                  ]),
              )
              : {},
          ]),
        );
      }
    } catch {
      console.warn("[RECONCILIATION] Configuration LipaPap invalide — vérification ignorée");
    }
  }
  return {
    clientKey,
    secretKey,
    paymentUrl,
    environment: environment === "production" ? "production" : "sandbox",
    action: "MOMO",
    networkIds: {},
    payoutProviderCodes,
    callbackUrl: callbackUrl || undefined,
    payerEmail: payerEmail || undefined,
  };
}

function normalized(value: unknown): string {
  return String(value || "").trim().toLowerCase();
}

/**
 * Do not infer a connector from a migrated gateway value alone.  This keeps
 * old rows from being sent to ClaPay after the startup gateway reassignment.
 */
function referenceBelongsTo(gateway: unknown, reference: unknown): boolean {
  const value = String(reference || "").trim().toUpperCase();
  switch (normalized(gateway)) {
    case "clapay":
      return value.startsWith("CP");
    case "mbiyo":
      return value.startsWith("MB");
    case "lipapap":
      return value.startsWith("LP");
    default:
      return false;
  }
}

function paymentStatus(value: unknown): string {
  return normalized(value);
}

async function creditConfirmedPayment(
  pending: any,
  txRef: string,
  providerTxId: string | null,
): Promise<boolean> {
  const cas = await financialPool.query(
    `UPDATE pending_payments
        SET status = 'gateway_confirmed'
      WHERE id = $1
        AND status IN ('gateway_pending', 'pending', 'submitted')
      RETURNING id`,
    [pending.id],
  );
  if (!cas.rowCount || await storage.getTransactionByTxId(txRef)) return false;

  const merchant = await storage.getMerchantById(pending.merchantId);
  const merchantCountry = await storage.findMerchantCountryBySimAndCountry(
    pending.merchantId,
    pending.country,
  );
  if (!merchantCountry) {
    console.error(`[RECONCILIATION] MerchantCountry introuvable — paiement #${pending.id}`);
    return false;
  }

  const credit = merchant?.customFeeRate != null
    ? Math.max(0, Math.floor(pending.amount * (1 - merchant.customFeeRate / 100)))
    : merchant?.feeExempt
      ? pending.amount
      : calcCredit(pending.amount, pending.country);
  const provider = resolveProviderCode(pending.gateway, pending.providerReference);

  await storage.incrementMerchantCountryBalance(merchantCountry.id, credit);
  await storage.createTransaction({
    merchantId: pending.merchantId,
    country: pending.country,
    txId: txRef,
    amount: pending.amount,
    payerNumber: pending.payerPhone || null,
    payerName: pending.payerName || null,
    status: "confirmed",
    provider,
    providerTxId,
    operator: pending.paymentMethod || null,
    providerReference: pending.providerReference || null,
    errorMessage: null,
    providerFee: pending.amount - credit,
  });
  notifyMerchantPayment(pending.merchantId, {
    txId: txRef,
    amount: pending.amount,
    payerNumber: pending.payerPhone,
    country: pending.country,
    provider,
  }).catch(() => {});
  notifyAdminPayment({
    txId: txRef,
    merchantName: merchant?.name || `#${pending.merchantId}`,
    payerNumber: pending.payerPhone,
    country: pending.country,
    amount: pending.amount,
    provider,
    status: "confirmed",
  }).catch(() => {});
  return true;
}

async function recordPaymentFailure(pending: any, txRef: string, providerTxId: string | null, status: string): Promise<void> {
  const cas = await financialPool.query(
    `UPDATE pending_payments
        SET status = 'gateway_failed'
      WHERE id = $1
        AND status IN ('gateway_pending', 'pending', 'submitted')
      RETURNING id`,
    [pending.id],
  );
  if (!cas.rowCount || await storage.getTransactionByTxId(txRef)) return;
  await storage.createTransaction({
    merchantId: pending.merchantId,
    country: pending.country,
    txId: txRef,
    amount: pending.amount,
    payerNumber: pending.payerPhone || null,
    payerName: pending.payerName || null,
    status: "failed",
    provider: resolveProviderCode(pending.gateway, pending.providerReference),
    providerTxId,
    operator: pending.paymentMethod || null,
    providerReference: pending.providerReference || null,
    errorMessage: `Paiement ${status} (vérification automatique)`,
    providerFee: 0,
  });
}

async function reconcilePayments(): Promise<void> {
  const rows = await storage.getPendingPayments();
  const now = Date.now();
  const threeMinutes = 3 * 60 * 1000;
  const fourHours = 4 * 60 * 60 * 1000;

  for (const pending of rows) {
    if (pending.status !== "gateway_pending" || !pending.providerReference) continue;
    const age = now - new Date(pending.createdAt).getTime();
    if (age < threeMinutes || age >= fourHours) continue;
    const gateway = normalized(pending.gateway);
    if (!referenceBelongsTo(gateway, pending.providerReference)) continue;

    try {
      if (gateway === "clapay") {
        const token = await getClapayKey();
        if (!token) continue;
        const providerTxId = pending.providerTxId || pending.providerReference;
        const result = await clapayGetTransactionStatus(token, providerTxId);
        const status = paymentStatus(result.status);
        if (PAYMENT_SUCCESS.has(status)) {
          await creditConfirmedPayment(pending, `CP-${pending.providerReference}`, providerTxId);
        } else if (PAYMENT_FAILURE.has(status)) {
          await recordPaymentFailure(pending, `CP-${pending.providerReference}`, providerTxId, status);
        }
      } else if (gateway === "mbiyo") {
        const token = await getMbiyoKey();
        if (!token) continue;
        const result: any = await mbiyoGetStatus(token, pending.providerReference);
        const status = paymentStatus(result?.data?.status || result?.status);
        if (PAYMENT_SUCCESS.has(status)) {
          await creditConfirmedPayment(pending, `MB-${pending.providerReference}`, pending.providerTxId || null);
        } else if (PAYMENT_FAILURE.has(status)) {
          await recordPaymentFailure(pending, `MB-${pending.providerReference}`, pending.providerTxId || null, status);
        }
      } else if (gateway === "lipapap") {
        const config = await getLipaPapConfig();
        if (!config) continue;
        const providerTxId = pending.providerTxId || pending.providerReference;
        const result = await getLipaPapTransactionStatus(config, providerTxId);
        const status = paymentStatus(result.status || result.result);
        if (PAYMENT_SUCCESS.has(status)) {
          await creditConfirmedPayment(
            pending,
            `LP-${result.trans_id || result.transaction_id || providerTxId}`,
            pending.providerTxId || providerTxId,
          );
        } else if (PAYMENT_FAILURE.has(status)) {
          await recordPaymentFailure(
            pending,
            `LP-${result.trans_id || result.transaction_id || providerTxId}`,
            pending.providerTxId || providerTxId,
            status,
          );
        }
      }
    } catch (error: any) {
      console.error(`[RECONCILIATION] Erreur paiement #${pending.id}:`, error?.message || error);
    }
  }
}

async function applyWithdrawalResult(withdrawal: any, status: string): Promise<void> {
  const normalizedStatus = paymentStatus(status);
  if (!WITHDRAWAL_SUCCESS.has(normalizedStatus) && !WITHDRAWAL_FAILURE.has(normalizedStatus)) return;

  const nextStatus = WITHDRAWAL_SUCCESS.has(normalizedStatus) ? "approved" : "failed";
  const cas = await financialPool.query(
    `UPDATE withdrawals
        SET status = $1
      WHERE id = $2 AND status = 'pending'
      RETURNING id`,
    [nextStatus, withdrawal.id],
  );
  if (!cas.rowCount) return;

  const reference = withdrawal.providerReference || null;
  const fees = WITHDRAWAL_SUCCESS.has(normalizedStatus) ? withdrawal.fees || 0 : 0;
  await storage.updateWithdrawalStatus(
    withdrawal.id,
    nextStatus,
    `Retrait ${nextStatus === "approved" ? "confirmé" : "refusé"} (${normalizedStatus})`,
    reference || undefined,
    fees,
    fees,
  );
  const merchant = await storage.getMerchantById(withdrawal.merchantId);
  if (nextStatus === "failed") {
    const merchantCountry = await storage.getMerchantCountryById(withdrawal.merchantCountryId);
    if (merchantCountry) {
      await storage.incrementMerchantCountryBalance(merchantCountry.id, withdrawal.amount);
    }
  }
  notifyAdminWithdrawal({
    id: withdrawal.id,
    merchantName: merchant?.name || `#${withdrawal.merchantId}`,
    country: withdrawal.country,
    amount: withdrawal.amount,
    fees,
    phone: withdrawal.phone,
    operator: withdrawal.operator,
    status: nextStatus,
    mode: "auto",
  }).catch(() => {});
  notifyMerchantWithdrawal(withdrawal.merchantId, {
    id: withdrawal.id,
    country: withdrawal.country,
    amount: withdrawal.amount,
    fees,
    phone: withdrawal.phone,
    operator: withdrawal.operator,
    status: nextStatus,
  }).catch(() => {});
}

async function reconcileStaleWithdrawals(): Promise<void> {
  const allPending = await storage.getPendingWithdrawals?.() || [];
  const now = Date.now();
  const oneMinute = 60 * 1000;
  const twentyFourHours = 24 * 60 * 60 * 1000;

  for (const withdrawal of allPending) {
    if (withdrawal.status !== "pending" || !withdrawal.providerReference) continue;
    const age = now - new Date(withdrawal.createdAt).getTime();
    if (age < oneMinute || age >= twentyFourHours) continue;
    const gateway = normalized(withdrawal.gateway);
    if (!referenceBelongsTo(gateway, withdrawal.providerReference)) continue;

    try {
      if (gateway === "mbiyo") {
        const token = await getMbiyoKey();
        if (!token) continue;
        const result: any = await mbiyoGetStatus(token, withdrawal.providerReference);
        await applyWithdrawalResult(
          withdrawal,
          String(result?.data?.status || result?.status || ""),
        );
      } else if (gateway === "lipapap") {
        const config = await getLipaPapConfig();
        if (!config?.payerEmail) continue;
        const result = await getLipaPapPayoutStatus(
          config,
          withdrawal.providerReference,
          config.payerEmail,
        );
        await applyWithdrawalResult(withdrawal, String(result.status || result.result || ""));
      }
    } catch (error: any) {
      console.error(`[RECONCILIATION-WD] Erreur retrait #${withdrawal.id}:`, error?.message || error);
    }
  }
}

export async function runReconciliation(): Promise<void> {
  await Promise.all([
    reconcilePayments().catch(error => console.error("[RECONCILIATION]", error)),
    reconcileStaleWithdrawals().catch(error => console.error("[RECONCILIATION-WD]", error)),
  ]);
}

export function startReconciliationJob(intervalMs = 5 * 60 * 1000): void {
  console.log(`[RECONCILIATION] Job démarré — vérification toutes les ${intervalMs / 60000}min`);
  setTimeout(() => runReconciliation().catch(() => {}), 60_000);
  setInterval(() => runReconciliation().catch(() => {}), intervalMs);
}