/**
 * Automatic status reconciliation for the active payment connectors.
 *
 * Only rows created by the current provider flows are eligible here.  In
 * particular, a legacy row which was assigned a new gateway during startup
 * migration is not enough to make it eligible for polling: its reference
 * must also have the prefix generated by that gateway.
 */
import { storage } from "./storage";
import { financialPool } from "./db";
import { getTransactionStatus as mbiyoGetStatus } from "./mbiyo";
import { clapayGetTransactionStatus } from "./clapay";
import {
  getLipaPapTransactionStatus,
  getLipaPapPayoutStatus,
  type LipaPapConfig,
} from "./lipapap";
import {
  getDrimpayConfig,
  getDrimpayPayinStatus,
  getDrimpayPayoutStatus,
  normalizeDrimpayStatus,
} from "./drimpay";
import { seapayQuery, SEAPAY_CURRENCY_COUNTRY } from "./seapay";
import {
  notifyAdminPayment,
  notifyAdminWithdrawal,
  notifyMerchantPayment,
  notifyMerchantWithdrawal,
} from "./telegram-bot";
import { resolveProviderCode } from "@shared/provider-labels";
import { calcMerchantCredit as calcCredit } from "./feeConfig";
import {
  AUTO_STATUS_CHECK_INTERVAL_MS,
  AUTO_STATUS_MAX_CHECKS,
  AUTO_TIMEOUT_ERROR_MARKER,
  isAutomaticStatusCheckDue,
  isAutomaticWithdrawal,
  isAutomaticWithdrawalStatusOpen,
  isManualPayinExpired,
  isPendingOperationExpired,
} from "./reconciliation-policy";

const PAYMENT_SUCCESS = new Set([
  "success", "successful", "completed", "complete", "paid", "approved",
  "confirmed", "settled",
]);
const PAYMENT_FAILURE = new Set([
  "failed", "failure", "cancelled", "canceled", "rejected", "declined",
  "error", "expired", "refund", "refunded", "reversal", "void",
]);
const WITHDRAWAL_SUCCESS = new Set([
  "completed", "success", "successful", "approved", "paid", "sent",
  "transferred", "processed", "delivered", "confirmed", "done", "ok",
]);
const WITHDRAWAL_FAILURE = new Set([
  "failed", "failure", "cancelled", "canceled", "rejected", "declined",
  "error", "expired", "reversed", "refunded", "refund",
]);

async function getConfiguredKey(envName: string, settingName: string): Promise<string | undefined> {
  return process.env[envName] || await storage.getSetting(settingName);
}

async function getMbiyoKey(): Promise<string | undefined> {
  return getConfiguredKey("MBIYO_API_KEY", "mbiyo_api_key");
}

async function getClapayKey(): Promise<string | undefined> {
  return getConfiguredKey("CLAPAY_API_KEY", "clapay_api_key");
}

async function getLipaPapConfig(): Promise<LipaPapConfig | undefined> {
  const [clientKey, secretKey, paymentUrl, callbackUrl, payerEmail, payoutCodesJson, environment] =
    await Promise.all([
      getConfiguredKey("LIPAPAP_CLIENT_KEY", "lipapap_client_key"),
      getConfiguredKey("LIPAPAP_SECRET_KEY", "lipapap_secret_key"),
      getConfiguredKey("LIPAPAP_PAYMENT_URL", "lipapap_payment_url"),
      storage.getSetting("lipapap_callback_url"),
      getConfiguredKey("LIPAPAP_PAYER_EMAIL", "lipapap_payer_email"),
      storage.getSetting("lipapap_payout_codes"),
      storage.getSetting("lipapap_environment"),
    ]);
  if (!clientKey || !secretKey || !paymentUrl) return undefined;

  let payoutProviderCodes: Record<string, Record<string, string>> = {};
  if (payoutCodesJson) {
    try {
      const parsed: unknown = JSON.parse(payoutCodesJson);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        payoutProviderCodes = Object.fromEntries(
          Object.entries(parsed).map(([country, operators]) => [
            country,
            operators && typeof operators === "object" && !Array.isArray(operators)
              ? Object.fromEntries(
                Object.entries(operators)
                  .filter((entry): entry is [string, string] =>
                    typeof entry[1] === "string" && entry[1].trim() !== "")
                  .map(([operator, code]) => [
                    operator.toLowerCase().replace(/[\s\-_]+/g, ""),
                    code.trim(),
                  ]),
              )
              : {},
          ]),
        );
      }
    } catch {
      console.warn("[RECONCILIATION] Configuration LipaPap invalide — vérification ignorée");
    }
  }
  return {
    clientKey,
    secretKey,
    paymentUrl,
    environment: environment === "production" ? "production" : "sandbox",
    action: "MOMO",
    networkIds: {},
    payoutProviderCodes,
    callbackUrl: callbackUrl || undefined,
    payerEmail: payerEmail || undefined,
  };
}

function normalized(value: unknown): string {
  return String(value || "").trim().toLowerCase();
}

/**
 * Do not infer a connector from a migrated gateway value alone.  This keeps
 * old rows from being sent to ClaPay after the startup gateway reassignment.
 */
function referenceBelongsTo(gateway: unknown, reference: unknown): boolean {
  const value = String(reference || "").trim().toUpperCase();
  switch (normalized(gateway)) {
    case "clapay":
      return value.startsWith("CP");
    case "mbiyo":
      return value.startsWith("MB");
    case "lipapap":
      return value.startsWith("LP");
    case "drimpay":
      return value.startsWith("DP-PAY-") || value.startsWith("DP-WD-");
    case "seapay":
      return value.startsWith("SP-");
    default:
      return false;
  }
}

function paymentStatus(value: unknown): string {
  return normalized(value);
}

async function creditConfirmedPayment(
  pending: any,
  txRef: string,
  providerTxId: string | null,
): Promise<boolean> {
  const cas = await financialPool.query(
    `UPDATE pending_payments
        SET status = 'gateway_confirmed'
      WHERE id = $1
        AND status IN ('gateway_pending', 'provider_pending', 'lipapap_pending', 'pending', 'submitted')
      RETURNING id`,
    [pending.id],
  );
  if (!cas.rowCount || await storage.getTransactionByTxId(txRef)) return false;

  const merchant = await storage.getMerchantById(pending.merchantId);
  const merchantCountry = await storage.findMerchantCountryBySimAndCountry(
    pending.merchantId,
    pending.country,
  );
  if (!merchantCountry) {
    console.error(`[RECONCILIATION] MerchantCountry introuvable — paiement #${pending.id}`);
    return false;
  }

  const credit = merchant?.customFeeRate != null
    ? Math.max(0, Math.floor(pending.amount * (1 - merchant.customFeeRate / 100)))
    : merchant?.feeExempt
      ? pending.amount
      : calcCredit(pending.amount, pending.country);
  const provider = resolveProviderCode(pending.gateway, pending.providerReference);

  await storage.incrementMerchantCountryBalance(merchantCountry.id, credit);
  await storage.createTransaction({
    merchantId: pending.merchantId,
    country: pending.country,
    txId: txRef,
    amount: pending.amount,
    payerNumber: pending.payerPhone || null,
    payerName: pending.payerName || null,
    status: "confirmed",
    provider,
    providerTxId,
    operator: pending.paymentMethod || null,
    providerReference: pending.providerReference || null,
    errorMessage: null,
    providerFee: pending.amount - credit,
    merchantCredit: credit,
  });
  notifyMerchantPayment(pending.merchantId, {
    txId: txRef,
    amount: pending.amount,
    payerNumber: pending.payerPhone,
    country: pending.country,
    provider,
  }).catch(() => {});
  notifyAdminPayment({
    txId: txRef,
    merchantName: merchant?.name || `#${pending.merchantId}`,
    payerNumber: pending.payerPhone,
    country: pending.country,
    amount: pending.amount,
    provider,
    status: "confirmed",
  }).catch(() => {});
  return true;
}

async function recordPaymentFailure(pending: any, txRef: string, providerTxId: string | null, status: string): Promise<void> {
  const cas = await financialPool.query(
    `UPDATE pending_payments
        SET status = 'gateway_failed'
      WHERE id = $1
        AND status IN ('gateway_pending', 'provider_pending', 'lipapap_pending', 'pending', 'submitted')
      RETURNING id`,
    [pending.id],
  );
  if (!cas.rowCount || await storage.getTransactionByTxId(txRef)) return;
  await storage.createTransaction({
    merchantId: pending.merchantId,
    country: pending.country,
    txId: txRef,
    amount: pending.amount,
    payerNumber: pending.payerPhone || null,
    payerName: pending.payerName || null,
    status: "failed",
    provider: resolveProviderCode(pending.gateway, pending.providerReference),
    providerTxId,
    operator: pending.paymentMethod || null,
    providerReference: pending.providerReference || null,
    errorMessage: `Paiement ${status} (vérification automatique)`,
    providerFee: 0,
  });
}

const OPEN_PENDING_PAYMENT_STATUSES = new Set([
  "gateway_pending",
  "provider_pending",
  "lipapap_pending",
  "pending",
  "submitted",
  "manual_waiting_submission",
  "manual_submitted",
]);

async function getSeapayMerchantId(country: string): Promise<string | undefined> {
  const envPrefix = `SEAPAY_${country.trim().toUpperCase().replace(/[^A-Z]/g, "")}`;
  const settingSuffix = country.trim().toLowerCase().replace(/[^a-z]/g, "");
  return getConfiguredKey(`${envPrefix}_MERCHANT_ID`, `seapay_merchant_id_${settingSuffix}`);
}

async function getSeapayApiKey(country: string): Promise<string | undefined> {
  const envPrefix = `SEAPAY_${country.trim().toUpperCase().replace(/[^A-Z]/g, "")}`;
  const settingSuffix = country.trim().toLowerCase().replace(/[^a-z]/g, "");
  return getConfiguredKey(`${envPrefix}_API_KEY`, `seapay_api_key_${settingSuffix}`);
}

async function claimPendingStatusCheck(pending: any): Promise<boolean> {
  if (!isAutomaticStatusCheckDue(
    Number(pending.autoStatusCheckCount || 0),
    pending.autoStatusCheckedAt,
    pending.createdAt,
    Date.now(),
  )) return false;

  const claimed = await financialPool.query(
    `UPDATE pending_payments
        SET auto_status_check_count = auto_status_check_count + 1,
            auto_status_checked_at = NOW()
      WHERE id = $1
        AND status = $2
        AND auto_status_check_count < $3
        AND (
          (auto_status_checked_at IS NULL AND created_at <= NOW() - ($4::double precision * INTERVAL '1 millisecond'))
          OR auto_status_checked_at <= NOW() - ($4::double precision * INTERVAL '1 millisecond')
        )
      RETURNING auto_status_check_count`,
    [pending.id, pending.status, AUTO_STATUS_MAX_CHECKS, AUTO_STATUS_CHECK_INTERVAL_MS],
  );
  return Boolean(claimed.rowCount);
}

async function markPendingPaymentTimedOut(pending: any): Promise<boolean> {
  const result = await financialPool.query(
    `UPDATE pending_payments
        SET status = 'gateway_failed',
            error_message = $3
      WHERE id = $1
        AND status = $2
        AND created_at <= NOW() - INTERVAL '3 hours'
      RETURNING id`,
    [pending.id, pending.status, AUTO_TIMEOUT_ERROR_MARKER],
  );
  return Boolean(result.rowCount);
}

async function reconcilePayments(): Promise<void> {
  const rows = await storage.getReconciliationPendingPayments();
  const now = Date.now();

  for (const pending of rows) {
    const status = normalized(pending.status);
    if (!OPEN_PENDING_PAYMENT_STATUSES.has(status)) continue;
    const gateway = normalized(pending.gateway);
    const isManual = gateway === "manual";

    const timedOut = isManual
      ? isManualPayinExpired(
          pending.createdAt,
          now,
        )
      : isPendingOperationExpired(pending.createdAt, now);
    if (timedOut) {
      await markPendingPaymentTimedOut(pending).catch(error =>
        console.error(`[RECONCILIATION] Expiration impossible pour le paiement #${pending.id}:`, (error as any)?.message || error),
      );
      continue;
    }

    if (isManual || !pending.providerReference) continue;
    if (Number(pending.autoStatusCheckCount || 0) >= AUTO_STATUS_MAX_CHECKS) continue;
    if (!isAutomaticStatusCheckDue(
      Number(pending.autoStatusCheckCount || 0),
      pending.autoStatusCheckedAt,
      pending.createdAt,
      now,
    )) continue;

    if (!referenceBelongsTo(gateway, pending.providerReference)) continue;

    try {
      if (gateway === "clapay") {
        const token = await getClapayKey();
        if (!token) continue;
        const providerTxId = pending.providerTxId || pending.providerReference;
        if (!await claimPendingStatusCheck(pending)) continue;
        const result = await clapayGetTransactionStatus(token, providerTxId);
        const status = paymentStatus(result.status);
        if (PAYMENT_SUCCESS.has(status)) {
          await creditConfirmedPayment(pending, `CP-${pending.providerReference}`, providerTxId);
        } else if (PAYMENT_FAILURE.has(status)) {
          await recordPaymentFailure(pending, `CP-${pending.providerReference}`, providerTxId, status);
        }
      } else if (gateway === "mbiyo") {
        const token = await getMbiyoKey();
        if (!token) continue;
        if (!await claimPendingStatusCheck(pending)) continue;
        const result: any = await mbiyoGetStatus(token, pending.providerReference);
        const status = paymentStatus(result?.data?.status || result?.status);
        if (PAYMENT_SUCCESS.has(status)) {
          await creditConfirmedPayment(pending, `MB-${pending.providerReference}`, pending.providerTxId || null);
        } else if (PAYMENT_FAILURE.has(status)) {
          await recordPaymentFailure(pending, `MB-${pending.providerReference}`, pending.providerTxId || null, status);
        }
      } else if (gateway === "lipapap") {
        const config = await getLipaPapConfig();
        if (!config) continue;
        const providerTxId = pending.providerTxId || pending.providerReference;
        if (!await claimPendingStatusCheck(pending)) continue;
        const result = await getLipaPapTransactionStatus(config, providerTxId);
        const status = paymentStatus(result.status || result.result);
        if (PAYMENT_SUCCESS.has(status)) {
          await creditConfirmedPayment(
            pending,
            `LP-${result.trans_id || result.transaction_id || providerTxId}`,
            pending.providerTxId || providerTxId,
          );
        } else if (PAYMENT_FAILURE.has(status)) {
          await recordPaymentFailure(
            pending,
            `LP-${result.trans_id || result.transaction_id || providerTxId}`,
            pending.providerTxId || providerTxId,
            status,
          );
        }
      } else if (gateway === "drimpay") {
        if (!pending.providerTxId) continue;
        const config = await getDrimpayConfig();
        if (!config) continue;
        if (!await claimPendingStatusCheck(pending)) continue;
        const result = await getDrimpayPayinStatus(config, pending.providerTxId);
        const status = paymentStatus(normalizeDrimpayStatus(result));
        if (PAYMENT_SUCCESS.has(status)) {
          await creditConfirmedPayment(
            pending,
            `DP-${pending.providerTxId}`,
            pending.providerTxId,
          );
        } else if (PAYMENT_FAILURE.has(status)) {
          await recordPaymentFailure(
            pending,
            `DP-${pending.providerTxId}`,
            pending.providerTxId,
            status,
          );
        }
      } else if (gateway === "seapay") {
        const [merchantId, apiKey] = await Promise.all([
          getSeapayMerchantId(pending.country),
          getSeapayApiKey(pending.country),
        ]);
        if (!merchantId || !apiKey) continue;
        if (!await claimPendingStatusCheck(pending)) continue;
        const result = await seapayQuery(
          merchantId,
          pending.providerReference,
          SEAPAY_CURRENCY_COUNTRY[pending.country] || "USD",
          apiKey,
        );
        const providerStatus = paymentStatus(result.data?.status);
        if (PAYMENT_SUCCESS.has(providerStatus)) {
          await creditConfirmedPayment(pending, `SP-${pending.providerReference}`, pending.providerTxId || null);
        } else if (PAYMENT_FAILURE.has(providerStatus)) {
          await recordPaymentFailure(pending, `SP-${pending.providerReference}`, pending.providerTxId || null, providerStatus);
        }
      }
    } catch (error: any) {
      console.error(`[RECONCILIATION] Erreur paiement #${pending.id}:`, error?.message || error);
    }
  }
}

async function applyWithdrawalResult(withdrawal: any, status: string): Promise<void> {
  const normalizedStatus = paymentStatus(status);
  if (!WITHDRAWAL_SUCCESS.has(normalizedStatus) && !WITHDRAWAL_FAILURE.has(normalizedStatus)) return;

  const nextStatus = WITHDRAWAL_SUCCESS.has(normalizedStatus) ? "approved" : "failed";
  const isDrimpayFailure = normalized(withdrawal.gateway) === "drimpay" && nextStatus === "failed";
  if (isDrimpayFailure) {
    const client = await financialPool.connect();
    let claimed = false;
    try {
      await client.query("BEGIN");
      const cas = await client.query(
        `UPDATE withdrawals
            SET status = 'failed'
          WHERE id = $1 AND status IN ('pending', 'processing')
          RETURNING id`,
        [withdrawal.id],
      );
      if (cas.rowCount) {
        const refund = await client.query(
          `UPDATE merchant_countries
              SET balance = balance + $1
            WHERE id = $2
            RETURNING id`,
          [withdrawal.amount, withdrawal.merchantCountryId],
        );
        if (!refund.rowCount) {
          throw new Error(`MerchantCountry introuvable pour le retrait Drimpay #${withdrawal.id}`);
        }
        claimed = true;
      }
      await client.query("COMMIT");
    } catch (error) {
      await client.query("ROLLBACK").catch(() => {});
      throw error;
    } finally {
      client.release();
    }
    if (!claimed) return;
  } else {
    const cas = await financialPool.query(
      `UPDATE withdrawals
          SET status = $1
        WHERE id = $2 AND status IN ('pending', 'processing')
        RETURNING id`,
      [nextStatus, withdrawal.id],
    );
    if (!cas.rowCount) return;
  }

  const reference = withdrawal.providerReference || null;
  const fees = WITHDRAWAL_SUCCESS.has(normalizedStatus) ? withdrawal.fees || 0 : 0;
  await storage.updateWithdrawalStatus(
    withdrawal.id,
    nextStatus,
    `Retrait ${nextStatus === "approved" ? "confirmé" : "refusé"} (${normalizedStatus})`,
    reference || undefined,
    fees,
    fees,
  );
  const merchant = await storage.getMerchantById(withdrawal.merchantId);
  if (nextStatus === "failed" && !isDrimpayFailure) {
    const merchantCountry = await storage.getMerchantCountryById(withdrawal.merchantCountryId);
    if (merchantCountry) {
      await storage.incrementMerchantCountryBalance(merchantCountry.id, withdrawal.amount);
    }
  }
  notifyAdminWithdrawal({
    id: withdrawal.id,
    merchantName: merchant?.name || `#${withdrawal.merchantId}`,
    country: withdrawal.country,
    amount: withdrawal.amount,
    fees,
    phone: withdrawal.phone,
    operator: withdrawal.operator,
    status: nextStatus,
    mode: "auto",
  }).catch(() => {});
  notifyMerchantWithdrawal(withdrawal.merchantId, {
    id: withdrawal.id,
    country: withdrawal.country,
    amount: withdrawal.amount,
    fees,
    phone: withdrawal.phone,
    operator: withdrawal.operator,
    status: nextStatus,
  }).catch(() => {});
}

async function reconcileStaleWithdrawals(): Promise<void> {
  const allPending = await storage.getReconciliationPendingWithdrawals();
  const now = Date.now();

  for (const withdrawal of allPending) {
    if (!isAutomaticWithdrawalStatusOpen(withdrawal.status)) continue;
    const gateway = normalized(withdrawal.gateway);
    if (!isAutomaticWithdrawal(withdrawal.withdrawalMode, gateway)) continue;

    if (isPendingOperationExpired(withdrawal.createdAt, now)) {
      await expireAutomaticWithdrawal(withdrawal).catch(error =>
        console.error(`[RECONCILIATION-WD] Expiration impossible pour le retrait #${withdrawal.id}:`, (error as any)?.message || error),
      );
      continue;
    }

    if (!withdrawal.providerReference) continue;
    if (Number(withdrawal.autoStatusCheckCount || 0) >= AUTO_STATUS_MAX_CHECKS) continue;
    if (!isAutomaticStatusCheckDue(
      Number(withdrawal.autoStatusCheckCount || 0),
      withdrawal.autoStatusCheckedAt,
      withdrawal.createdAt,
      now,
    )) continue;
    if (!referenceBelongsTo(gateway, withdrawal.providerReference)) continue;

    try {
      if (gateway === "clapay") {
        const token = await getClapayKey();
        if (!token) continue;
        if (!await claimWithdrawalStatusCheck(withdrawal)) continue;
        const result = await clapayGetTransactionStatus(
          token,
          withdrawal.providerTxId || withdrawal.providerReference,
        );
        await applyWithdrawalResult(withdrawal, String(result.status || ""));
      } else if (gateway === "mbiyo") {
        const token = await getMbiyoKey();
        if (!token) continue;
        if (!await claimWithdrawalStatusCheck(withdrawal)) continue;
        const result: any = await mbiyoGetStatus(token, withdrawal.providerReference);
        await applyWithdrawalResult(
          withdrawal,
          String(result?.data?.status || result?.status || ""),
        );
      } else if (gateway === "lipapap") {
        const config = await getLipaPapConfig();
        if (!config?.payerEmail) continue;
        if (!await claimWithdrawalStatusCheck(withdrawal)) continue;
        const result = await getLipaPapPayoutStatus(
          config,
          withdrawal.providerReference,
          config.payerEmail,
        );
        await applyWithdrawalResult(withdrawal, String(result.status || result.result || ""));
      } else if (gateway === "drimpay") {
        if (!withdrawal.providerTxId) continue;
        const config = await getDrimpayConfig();
        if (!config) continue;
        if (!await claimWithdrawalStatusCheck(withdrawal)) continue;
        const result = await getDrimpayPayoutStatus(config, withdrawal.providerTxId);
        await applyWithdrawalResult(withdrawal, normalizeDrimpayStatus(result));
      } else if (gateway === "seapay") {
        const [merchantId, apiKey] = await Promise.all([
          getSeapayMerchantId(withdrawal.country),
          getSeapayApiKey(withdrawal.country),
        ]);
        if (!merchantId || !apiKey) continue;
        if (!await claimWithdrawalStatusCheck(withdrawal)) continue;
        const result = await seapayQuery(
          merchantId,
          withdrawal.providerReference,
          SEAPAY_CURRENCY_COUNTRY[withdrawal.country] || "USD",
          apiKey,
        );
        await applyWithdrawalResult(withdrawal, String(result.data?.status || ""));
      }
    } catch (error: any) {
      console.error(`[RECONCILIATION-WD] Erreur retrait #${withdrawal.id}:`, error?.message || error);
    }
  }
}

async function claimWithdrawalStatusCheck(withdrawal: any): Promise<boolean> {
  if (!isAutomaticStatusCheckDue(
    Number(withdrawal.autoStatusCheckCount || 0),
    withdrawal.autoStatusCheckedAt,
    withdrawal.createdAt,
    Date.now(),
  )) return false;

  const claimed = await financialPool.query(
    `UPDATE withdrawals
        SET auto_status_check_count = auto_status_check_count + 1,
            auto_status_checked_at = NOW()
      WHERE id = $1
        AND status IN ('pending', 'processing')
        AND withdrawal_mode = 'auto'
        AND auto_status_check_count < $2
        AND (
          (auto_status_checked_at IS NULL AND created_at <= NOW() - ($3::double precision * INTERVAL '1 millisecond'))
          OR auto_status_checked_at <= NOW() - ($3::double precision * INTERVAL '1 millisecond')
        )
      RETURNING auto_status_check_count`,
    [withdrawal.id, AUTO_STATUS_MAX_CHECKS, AUTO_STATUS_CHECK_INTERVAL_MS],
  );
  return Boolean(claimed.rowCount);
}

async function expireAutomaticWithdrawal(withdrawal: any): Promise<void> {
  const client = await financialPool.connect();
  let expired = false;
  try {
    await client.query("BEGIN");
    const claimed = await client.query(
      `UPDATE withdrawals
          SET status = 'failed',
              admin_note = 'Délai maximal de 3 heures dépassé; solde recrédité.',
              processed_at = NOW()
        WHERE id = $1
          AND status IN ('pending', 'processing')
          AND withdrawal_mode = 'auto'
          AND created_at <= NOW() - INTERVAL '3 hours'
        RETURNING id`,
      [withdrawal.id],
    );
    if (claimed.rowCount) {
      const refunded = await client.query(
        `UPDATE merchant_countries
            SET balance = balance + $1
          WHERE id = $2
          RETURNING id`,
        [Number(withdrawal.amount || 0) + Number(withdrawal.fees || 0), withdrawal.merchantCountryId],
      );
      if (!refunded.rowCount) {
        throw new Error(`MerchantCountry introuvable pour le retrait expiré #${withdrawal.id}`);
      }
      expired = true;
    }
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK").catch(() => {});
    throw error;
  } finally {
    client.release();
  }

  if (!expired) return;
  const merchant = await storage.getMerchantById(withdrawal.merchantId);
  notifyAdminWithdrawal({
    id: withdrawal.id,
    merchantName: merchant?.name || `#${withdrawal.merchantId}`,
    country: withdrawal.country,
    amount: withdrawal.amount,
    fees: 0,
    phone: withdrawal.phone,
    operator: withdrawal.operator,
    status: "failed",
    mode: "auto",
  }).catch(() => {});
  notifyMerchantWithdrawal(withdrawal.merchantId, {
    id: withdrawal.id,
    country: withdrawal.country,
    amount: withdrawal.amount,
    fees: 0,
    phone: withdrawal.phone,
    operator: withdrawal.operator,
    status: "failed",
  }).catch(() => {});
}

export async function runReconciliation(): Promise<void> {
  if (reconciliationRunning) return;
  reconciliationRunning = true;
  try {
    await Promise.all([
      reconcilePayments().catch(error => console.error("[RECONCILIATION]", error)),
      reconcileStaleWithdrawals().catch(error => console.error("[RECONCILIATION-WD]", error)),
    ]);
  } finally {
    reconciliationRunning = false;
  }
}

let reconciliationTimer: ReturnType<typeof setInterval> | null = null;
let reconciliationRunning = false;

export function startReconciliationJob(intervalMs = AUTO_STATUS_CHECK_INTERVAL_MS): void {
  if (reconciliationTimer) clearInterval(reconciliationTimer);
  console.log(`[RECONCILIATION] Job démarré — vérification toutes les ${intervalMs / 1000}s`);
  void runReconciliation().catch(() => {});
  reconciliationTimer = setInterval(() => void runReconciliation().catch(() => {}), intervalMs);
  reconciliationTimer.unref?.();
}